// EGX Stocks - 269 companies
// Auto-generated from official EGX data
// Usage: import { EGX_STOCKS, getStockName } from './egxStocks'

export interface EGXStock {
  ticker: string;
  nameAr: string;
  nameEn: string;
  descriptionAr?: string;
  descriptionEn?: string;
}

export const EGX_STOCKS: EGXStock[] = [
  { ticker: "ABUK", nameAr: "أبو قير للأسمدة", nameEn: "Abu Qir Fertilizers" },
  { ticker: "ADIB", nameAr: "بنك أبوظبي الإسلامي مصر", nameEn: "Abu Dhabi Islamic Bank Egypt" },
  { ticker: "ACRO", nameAr: "أكرو مصر", nameEn: "Acrow Misr" },
  { ticker: "APPC", nameAr: "التعبئة الدوائية المتقدمة", nameEn: "Advanced Pharmaceutical Packaging Co." },
  { ticker: "AJWA", nameAr: "عجوة للصناعات الغذائية", nameEn: "Ajwa For Food Industries Company Egypt" },
  { ticker: "SAUD", nameAr: "بنك البركة مصر", nameEn: "Al Baraka Bank Egypt" },
  { ticker: "FNAR", nameAr: "الفنار للمقاولات والتجارة", nameEn: "Al Fanar Contracting, Construction, Trade, Import And Export" },
  { ticker: "AMPI", nameAr: "المعاصر للبرمجة ونشر المعلومات", nameEn: "Al Moasher For Programming And Information Dissemination" },
  { ticker: "ATLC", nameAr: "التوفيق للتأجير التمويلي", nameEn: "Al Tawfeek Leasing Company - A.T.Lease" },
  { ticker: "ALEXA", nameAr: "أسمنت الإسكندرية", nameEn: "Alexandria Cement" },
  { ticker: "ALCN", nameAr: "الإسكندرية للحاويات والبضائع", nameEn: "Alexandria Containers And Goods" },
  { ticker: "AFMC", nameAr: "مطاحن الإسكندرية", nameEn: "Alexandria Flour Mills" },
  { ticker: "AMOC", nameAr: "الإسكندرية للزيوت المعدنية", nameEn: "Alexandria Mineral Oils Company" },
  { ticker: "ANFI", nameAr: "الإسكندرية الوطنية للاستثمارات المالية", nameEn: "Alexandria National Company For Financial Investments" },
  { ticker: "AMES", nameAr: "المركز الطبي الجديد بالإسكندرية", nameEn: "Alexandria New Medical Center" },
  { ticker: "AXPH", nameAr: "الإسكندرية للأدوية والصناعات الكيماوية", nameEn: "Alexandria Co for Pharmaceutical and Chemical Industries" },
  { ticker: "SPIN", nameAr: "الإسكندرية للغزل والنسيج", nameEn: "Alexandria Spinning & Weaving (SPINALEX)" },
  { ticker: "AMEC", nameAr: "أميكو للصناعات الطبية", nameEn: "Ameco Medical Industries" },
  { ticker: "AMER", nameAr: "أمير جروب القابضة", nameEn: "Amer Group Holding" },
  { ticker: "ALUM", nameAr: "العربية للألومنيوم", nameEn: "Arab Aluminum" },
  { ticker: "CERA", nameAr: "السيراميك العربي", nameEn: "Arab Ceramic" },
  { ticker: "ACGC", nameAr: "العربية لحليج الأقطان", nameEn: "Arab Cotton Ginning" },
  { ticker: "AMIA", nameAr: "العرب للملتقى الاستثماري", nameEn: "Arab Moltaka Investments Co." },
  { ticker: "ADCI", nameAr: "العربية للأدوية والصناعات الكيماوية", nameEn: "Arab Drug Company for Pharmaceuticals and Chemical" },
  { ticker: "APSW", nameAr: "العربية للغزل والنسيج بولفارا", nameEn: "Arab Polvara Spinning And Weaving" },
  { ticker: "RREI", nameAr: "العربية للاستثمار العقاري", nameEn: "Arab Real Estate Investment Co." },
  { ticker: "ARVA", nameAr: "العربية للصمامات", nameEn: "Arab Valves Company" },
  { ticker: "AIND", nameAr: "استثمارات العربية للتنمية", nameEn: "Arabia Investments Development Financial Investments Holding" },
  { ticker: "ARCC", nameAr: "الأسمنت العربية", nameEn: "Arabian Cement Company" },
  { ticker: "ASCM", nameAr: "أسيك للتعدين", nameEn: "Asek Company For Mining - Ascom" },
  { ticker: "AITG", nameAr: "أسيوط الإسلامية للتجارة والتنمية", nameEn: "Assiut Islamic National Trade and Development" },
  { ticker: "ALRA", nameAr: "أطلس لاستصلاح الأراضي", nameEn: "Atlas For Land Reclamation And Agricultural Processing" },
  { ticker: "BIGP", nameAr: "المجموعة الاستثمارية البربرية", nameEn: "El Barbary Investment Group (BIG)" },
  { ticker: "BTFH", nameAr: "بلتون المالية القابضة", nameEn: "Beltone Financial Holding" },
  { ticker: "BCAP", nameAr: "بلتون كابيتال للاستثمارات المالية", nameEn: "Beltone Capital Holding For Financial Investments" },
  { ticker: "BSFR", nameAr: "التضامن للإسكان والأمن الغذائي", nameEn: "Brothers Solidarity For Real Estate Investment And Food Security" },
  { ticker: "CIRF", nameAr: "القاهرة للتنمية والاستثمار", nameEn: "Cairo Development and Investment" },
  { ticker: "CAED", nameAr: "القاهرة للخدمات التعليمية", nameEn: "Cairo Educational Services" },
  { ticker: "COSG", nameAr: "القاهرة للزيوت والصابون", nameEn: "Cairo Oils & Soap" },
  { ticker: "CPCI", nameAr: "القاهرة للأدوية والصناعات الكيماوية", nameEn: "Cairo Pharmaceuticals and Chemical Industries" },
  { ticker: "POUL", nameAr: "القاهرة للدواجن", nameEn: "Cairo Poultry" },
  { ticker: "CSAG", nameAr: "وكالات قناة السويس للملاحة", nameEn: "Canal Shipping Agencies" },
  { ticker: "PRCL", nameAr: "السيراميك والبورسلين", nameEn: "Ceramic & Porcelain" },
  { ticker: "CCAP", nameAr: "قلعة القابضة", nameEn: "Qalaa Holdings" },
  { ticker: "CCAPP", nameAr: "قلعة القابضة - أسهم ممتازة", nameEn: "Qalaa Holdings - Preferred Shares" },
  { ticker: "COMI", nameAr: "البنك التجاري الدولي", nameEn: "Commercial International Bank (Egypt)" },
  { ticker: "CIEB", nameAr: "كريدي أجريكول مصر", nameEn: "Credit Agricole Egypt" },
  { ticker: "DCRC", nameAr: "دلتا للإنشاء وإعادة الإعمار", nameEn: "Delta Construction & Rebuilding" },
  { ticker: "DTPP", nameAr: "دلتا للطباعة والتغليف", nameEn: "Delta Co for Printing and Packaging" },
  { ticker: "DEIN", nameAr: "دلتا للتأمين", nameEn: "Delta Insurance" },
  { ticker: "SUGR", nameAr: "دلتا للسكر", nameEn: "Delta Sugar" },
  { ticker: "DAPH", nameAr: "الدلتا للاستشارات الهندسية", nameEn: "Development & Engineering Consultants" },
  { ticker: "DSCW", nameAr: "دايس للملابس الرياضية وال casual", nameEn: "Dice Sport & Casual Wear" },
  { ticker: "EDFM", nameAr: "مطاحن شرق الدلتا", nameEn: "East Delta Flour Mills" },
  { ticker: "EAST", nameAr: "الشرقية للدخان", nameEn: "Eastern Tobacco" },
  { ticker: "EFID", nameAr: "إديتا للصناعات الغذائية", nameEn: "Edita Food Industries" },
  { ticker: "HRHO", nameAr: "هيرمس القابضة", nameEn: "EFG Hermes Holding Company" },
  { ticker: "EGX30ETF", nameAr: "صندوق مؤشر EGX 30", nameEn: "Egx 30 Index Etf" },
  { ticker: "EGAL", nameAr: "مصر للألومنيوم", nameEn: "Egypt Aluminum Company" },
  { ticker: "EPCO", nameAr: "مصر للدواجن", nameEn: "Egypt For Poultry" },
  { ticker: "MISR", nameAr: "مصر القارية للجرانيت والرخام", nameEn: "Egypt Intercontinental for Granite and Marble" },
  { ticker: "ESAC", nameAr: "مصر جنوب أفريقيا للاتصالات", nameEn: "Egypt-South Africa For Communication" },
  { ticker: "EASB", nameAr: "المصرية العربية ثمار للسمسرة", nameEn: "Egyptian Arabian Company Themar for Securities Brokerage" },
  { ticker: "EGCH", nameAr: "الشركة المصرية للصناعات الكيماوية (كيما)", nameEn: "Egyptian Chemical Industries (Kima)" },
  { ticker: "OREG", nameAr: "أورنج مصر للاتصالات", nameEn: "Orange Egypt for Telecommunications" },
  { ticker: "EFIC", nameAr: "المصرية المالية والصناعية", nameEn: "Egyptian Financial & Industrial" },
  { ticker: "EDBM", nameAr: "المصرية لتطوير مواد البناء", nameEn: "Egyptian For Developing Building Materials" },
  { ticker: "EGTS", nameAr: "المصرية للمنتجعات السياحية", nameEn: "Egyptian For Tourism Resorts" },
  { ticker: "EGBE", nameAr: "البنك المصري الخليجي", nameEn: "Egyptian Gulf Bank" },
  { ticker: "PHAR", nameAr: "المصرية الدولية للأدوية", nameEn: "Egyptian International Pharmaceuticals Industries" },
  { ticker: "EITP", nameAr: "المصرية للمشروعات السياحية الدولية", nameEn: "Egyptian Company for International Touristic Projects" },
  { ticker: "IRON", nameAr: "المصرية للحديد والصلب", nameEn: "Egyptian Iron & Steel" },
  { ticker: "EKHO", nameAr: "المصرية الكويتية القابضة", nameEn: "Egyptian Kuwait Holding" },
  { ticker: "MPRC", nameAr: "المدينة الإعلامية", nameEn: "Egyptian Media Production City" },
  { ticker: "MOED", nameAr: "المصرية للتعليم الحديث", nameEn: "Egyptian Modern Education Systems" },
  { ticker: "AREH", nameAr: "التجمع المصري العقاري", nameEn: "Real Estate Egyptian Consortium" },
  { ticker: "AREHA", nameAr: "التجمع المصري العقاري لحاملي الأسهم", nameEn: "Real Estate Egyptian Consortium Bearer Shares" },
  { ticker: "EGSA", nameAr: "المصرية للأقمار الصناعية (نيل سات)", nameEn: "Egyptian Satellites (NileSat)" },
  { ticker: "ESGI", nameAr: "المصرية للنشا والجلوكوز", nameEn: "Egyptian Starch & Glucose" },
  { ticker: "ETRS", nameAr: "المصرية للنقل والخدمات التجارية", nameEn: "Egyptian Transport & Commercial Services" },
  { ticker: "ABRD", nameAr: "المصريين بالخارج للاستثمار والتنمية", nameEn: "Egyptians Abroad For Investment & Development" },
  { ticker: "EIUD", nameAr: "المصريين للاستثمار والتنمية العمرانية", nameEn: "Egyptians For Investment & Urban Development" },
  { ticker: "EHDR", nameAr: "المصريين للإسكان والتعمير", nameEn: "Egyptians for Housing Development" },
  { ticker: "AFDI", nameAr: "الأهلي للتنمية والاستثمار", nameEn: "Al Ahly for Development & Investment" },
  { ticker: "EPPK", nameAr: "الأهرام للطباعة والتغليف", nameEn: "El Ahram Co. For Printing And Packing" },
  { ticker: "EEII", nameAr: "الصناعات الهندسية العربية", nameEn: "Arab Engineering Industries" },
  { ticker: "EALR", nameAr: "العربية لاستصلاح الأراضي", nameEn: "El Arabia For Land Reclamation" },
  { ticker: "EBDP", nameAr: "البدر للبلاستيك", nameEn: "El Badr Plastic" },
  { ticker: "ICFC", nameAr: "الدولية للأسمدة والكيماويات", nameEn: "El Dawlia Fertilizers And Chemicals" },
  { ticker: "IRAX", nameAr: "العز الدخيلة للصلب - الإسكندرية", nameEn: "El Ezz Aldekhela Steel - Alexandria" },
  { ticker: "ECAP", nameAr: "العز للسيراميك والبورسلين (جيما)", nameEn: "El Ezz Ceramics & Porcelain (Gemma)" },
  { ticker: "KWIN", nameAr: "القاهرة الوطنية للاستثمار", nameEn: "El Kahera El Watania Investment" },
  { ticker: "ELKA", nameAr: "القاهرة للإسكان", nameEn: "El Kahera Housing" },
  { ticker: "KABO", nameAr: "النصر للملابس والمنسوجات - كابو", nameEn: "El Nasr Clothes & Textiles - KABO" },
  { ticker: "ELNA", nameAr: "النصر لصناعة المحاصيل الزراعية", nameEn: "El Nasr For Manufacturing Agricultural Crops" },
  { ticker: "NASR", nameAr: "النصر للمحولات (الماكو)", nameEn: "El Nasr Transformers (El Maco)" },
  { ticker: "OBRI", nameAr: "العبور للاستثمار العقاري", nameEn: "El Ebour Real Estate Investment" },
  { ticker: "EOSB", nameAr: "العروبة للسمسرة", nameEn: "Al Orouba Securities Brokerage" },
  { ticker: "ELSH", nameAr: "الشمس للإسكان والتعمير", nameEn: "El Shams Housing & Urbanization" },
  { ticker: "SPHT", nameAr: "الشمس للأهرامات للفنادق والمشروعات السياحية", nameEn: "El Shams Pyramids For Hotels & Touristic Projects" },
  { ticker: "ELWA", nameAr: "الوادي للتنمية السياحية", nameEn: "El Wadi Touristic Development" },
  { ticker: "NIPH", nameAr: "النيل للأدوية والصناعات الكيماوية", nameEn: "El-Nile Co. For Pharmaceuticals And Chemical Industries" },
  { ticker: "ELEC", nameAr: "الكابلات الكهربائية المصرية", nameEn: "Electro Cable Egypt Company" },
  { ticker: "UEGC", nameAr: "السعيد للمقاولات والاستثمار العقاري", nameEn: "El Saeed Contracting and Real Estate Investment" },
  { ticker: "SWDY", nameAr: "السويدى للكهرباء", nameEn: "El Sewedy Electric Company" },
  { ticker: "EMFD", nameAr: "إعمار مصر للتنمية", nameEn: "Emaar Misr For Development" },
  { ticker: "ENGC", nameAr: "الصناعات الهندسية (أيكون)", nameEn: "Engineering Industries (Icon)" },
  { ticker: "EXPA", nameAr: "بنك تنمية الصادرات", nameEn: "Export Development Bank Of Egypt" },
  { ticker: "ZEOT", nameAr: "الزيوت والمستخلصات", nameEn: "Extracted Oils & Derivatives" },
  { ticker: "ESRS", nameAr: "العز للصلب", nameEn: "Ezz Steel" },
  { ticker: "FAIT", nameAr: "بنك فيصل الإسلامي المصري (جنيه)", nameEn: "Faisal Islamic Bank Of Egypt (EGP)" },
  { ticker: "FAITA", nameAr: "بنك فيصل الإسلامي المصري (دولار)", nameEn: "Faisal Islamic Bank Of Egypt (USD)" },
  { ticker: "FERC", nameAr: "فيركيم مصر للأسمدة والكيماويات", nameEn: "Ferchem Misr Company for Fertilizers and Chemicals" },
  { ticker: "FIRED", nameAr: "الأولى للاستثمار والتنمية العقارية", nameEn: "First Investment And Real Estate Development" },
  { ticker: "AUTO", nameAr: "جي بي أوتو", nameEn: "GB Auto" },
  { ticker: "AALR", nameAr: "العامة لاستصلاح الأراضي والتنمية", nameEn: "General Co for Land Reclamation Development and Reconstruction" },
  { ticker: "GSSC", nameAr: "العامة للصوامع والتخزين", nameEn: "General Company for Silos and Storage" },
  { ticker: "GETO", nameAr: "جينيل تورز", nameEn: "Genial Tours" },
  { ticker: "GIHD", nameAr: "غربيه الإسلامية للإسكان", nameEn: "Gharbia Islamic Housing Development" },
  { ticker: "GGCC", nameAr: "الجيزة العامة للمقاولات", nameEn: "Giza General Contracting" },
  { ticker: "BIOC", nameAr: "جلاكسو سميث كلاين", nameEn: "Glaxo Smith Kline" },
  { ticker: "GTHE", nameAr: "جلوبال للاتصالات القابضة", nameEn: "Global Telecom Holding" },
  { ticker: "GMCI", nameAr: "جي ام سي للاستثمارات الصناعية والتجارية", nameEn: "GMC Group For Industrial, Commercial And Financial Investments" },
  { ticker: "GOCO", nameAr: "الساحل الذهبي", nameEn: "Golden Coast Company" },
  { ticker: "GPPL", nameAr: "الميادين الذهبية", nameEn: "Golden Pyramids Plaza" },
  { ticker: "GTWL", nameAr: "الذهبية للمنسوجات والملابس الصوفية", nameEn: "Golden Textiles & Clothes Wool" },
  { ticker: "GRCA", nameAr: "جراند كابيتال للاستثمار", nameEn: "Grand Investment Capital" },
  { ticker: "AGIN", nameAr: "الاستثمار الخليجي العربي", nameEn: "Gulf Arab Investment" },
  { ticker: "CCRS", nameAr: "الخليج الكندي للاستثمار العقاري", nameEn: "Gulf Canadian Real Estate Investment Co." },
  { ticker: "HELI", nameAr: "هليوبوليس للإسكان والتعمير", nameEn: "Heliopolis Housing" },
  { ticker: "HDBK", nameAr: "بنك الإسكان والتعمير", nameEn: "Housing & Development Bank" },
  { ticker: "INEE", nameAr: "إندس والهندسة", nameEn: "Indus & Engineer" },
  { ticker: "INEG", nameAr: "المتكاملة للهندسة", nameEn: "Integrated Engineering Group Sae" },
  { ticker: "ICAL", nameAr: "إنتر-القاهرة للألومنيوم", nameEn: "Inter-Cairo For Aluminum Industry" },
  { ticker: "IFAP", nameAr: "المنتجات الزراعية الدولية", nameEn: "International Agricultural Products" },
  { ticker: "IBCT", nameAr: "المؤسسة الدولية للتجارة والامتياز", nameEn: "International Business Corporation For Trade And Franchise" },
  { ticker: "ICID", nameAr: "الدولية للاستثمار والتنمية", nameEn: "International Co For Investment & Development" },
  { ticker: "ICLE", nameAr: "الدولية للتأجير التمويلي (إنكوليز)", nameEn: "International Company For Leasing (Incolease)" },
  { ticker: "ICMI", nameAr: "الدولية للصناعات الطبية", nameEn: "International Company For Medical Industries" },
  { ticker: "DIFC", nameAr: "ثاني أكسيد الكربون الجاف الدولي", nameEn: "International Dry Ice" },
  { ticker: "IPPM", nameAr: "الدولية لمواد الطباعة والتغليف", nameEn: "International Printing & Packaging Materials Co." },
  { ticker: "IDRE", nameAr: "الإسماعيلية للتنمية والعقارات", nameEn: "Ismailia Development And Real Estate" },
  { ticker: "ISMA", nameAr: "الإسماعيلية مصر للدواجن", nameEn: "Ismailia Misr Poultry" },
  { ticker: "INFI", nameAr: "الإسماعيلية الوطنية للصناعات الغذائية", nameEn: "Ismailia National Food Industries" },
  { ticker: "ITSY", nameAr: "آي تي سينرجي", nameEn: "IT Synergy" },
  { ticker: "JUFO", nameAr: "جهينة للصناعات الغذائية", nameEn: "Juhayna Food Industries" },
  { ticker: "KZPC", nameAr: "كفر الزيات للمبيدات والكيماويات", nameEn: "Kafr El Zayat Pesticides and Chemicals" },
  { ticker: "LKGP", nameAr: "مجموعة لاقا", nameEn: "Lakah Group" },
  { ticker: "LCSW", nameAr: "ليسيكو مصر", nameEn: "Lecico Egypt" },
  { ticker: "MPCO", nameAr: "المنصورة للدواجن", nameEn: "Mansoura Poultry" },
  { ticker: "MOIL", nameAr: "موريديف وخدمات النفط", nameEn: "Maridive & Oil Services" },
  { ticker: "MMAT", nameAr: "مرسى مرسى علم للتنمية السياحية", nameEn: "Marsa Marsa Alam For Tourism Development" },
  { ticker: "MAAL", nameAr: "مرسيليا المصريه الخليجية القابضة", nameEn: "Marseille Almasreia Alkhalegeya For Holding Investment" },
  { ticker: "MBEN", nameAr: "إم بي للهندسة", nameEn: "MB Engineering" },
  { ticker: "MEPA", nameAr: "التعبئة الطبية", nameEn: "Medical Packaging Company" },
  { ticker: "MNHD", nameAr: "مدينة نصر للإسكان", nameEn: "Medinet Nasr Housing" },
  { ticker: "MPCI", nameAr: "ممفيس للأدوية", nameEn: "Memphis Pharmaceuticals" },
  { ticker: "MENA", nameAr: "مينا للاستثمار السياحي والعقاري", nameEn: "Mena Touristic & Real Estate Investment" },
  { ticker: "WCDF", nameAr: "مطاحن وسط وغرب الدلتا", nameEn: "Middle & West Delta Flour Mills" },
  { ticker: "MEGM", nameAr: "الشرق الأوسط لصناعة الزجاج", nameEn: "Middle East Glass Manufacturing" },
  { ticker: "CEFM", nameAr: "مطاحن مصر الوسطى", nameEn: "Middle Egypt Flour Mills" },
  { ticker: "MIPH", nameAr: "مينافارم للأدوية", nameEn: "Minapharm Pharmaceuticals" },
  { ticker: "MBSC", nameAr: "مصر بني سويف للإسمنت", nameEn: "Misr Beni Suef Cement" },
  { ticker: "MCQE", nameAr: "مصر للإسمنت قنا", nameEn: "Misr Cement (Qena)" },
  { ticker: "MICH", nameAr: "مصر للصناعات الكيماوية", nameEn: "Misr Chemical Industries" },
  { ticker: "MRCO", nameAr: "مصر للتبريد وتكييف الهواء", nameEn: "Misr Refrigeration and Air Conditioning" },
  { ticker: "MFSC", nameAr: "مصر فري شوب", nameEn: "Egypt Free Shops" },
  { ticker: "MEDA", nameAr: "مصر السلام للتنمية والتكنولوجيا", nameEn: "Misr Elsalam For Development & Advanced Technology" },
  { ticker: "MFINEG", nameAr: "مصر للاستثمارات المالية", nameEn: "Misr Financial Investments" },
  { ticker: "MFPC", nameAr: "مصر لإنتاج الأسمدة", nameEn: "Misr Fertilizers Production Company" },
  { ticker: "MHOT", nameAr: "مصر للفنادق", nameEn: "Misr Hotels" },
  { ticker: "MKIT", nameAr: "مصر الكويت للاستثمار والتجارة (ميتيلو)", nameEn: "Misr Kuwait Investment And Trading (Meatello)" },
  { ticker: "ATQA", nameAr: "مصر الوطنية للصلب - العتاقة", nameEn: "Misr National Steel - Ataqa" },
  { ticker: "MOSC", nameAr: "مصر للزيوت والصابون", nameEn: "Misr Oils & Soap" },
  { ticker: "WATP", nameAr: "الحديثة للموانع المائية", nameEn: "Modern Waterproofing Company" },
  { ticker: "SMPP", nameAr: "الشروق للطباعة الحديثة والتغليف", nameEn: "Shorouk for Modern Printing and Packaging" },
  { ticker: "MOIN", nameAr: "المهندس للتأمين", nameEn: "Mohandes Insurance" },
  { ticker: "NAHO", nameAr: "نعيم القابضة", nameEn: "NAEEM Holding" },
  { ticker: "NCCW", nameAr: "النصر لأعمال المدنية", nameEn: "Nasr Company For Civil Works" },
  { ticker: "NBKE", nameAr: "البنك الوطني الكويتي مصر", nameEn: "National Bank Of Kuwait Egypt" },
  { ticker: "NCEM", nameAr: "الإسمنت الوطنية", nameEn: "National Cement" },
  { ticker: "NCMP", nameAr: "الوطنية لمنتجات الذرة", nameEn: "National Company For Maize Products" },
  { ticker: "NDRL", nameAr: "الوطنية للحفر", nameEn: "National Drilling Company" },
  { ticker: "NHPS", nameAr: "الإسكان الوطني للنقابات المهنية", nameEn: "National Housing for Professional Syndicates" },
  { ticker: "COPR", nameAr: "النحاس للاستثمار والتطوير العقاري", nameEn: "Copper For Commercial Investment & Real Estate Development" },
  { ticker: "EGAS", nameAr: "الشركة المصرية للغاز", nameEn: "Egypt Gas Company" },
  { ticker: "NCIS", nameAr: "نيوكاسل للاستثمار الرياضي", nameEn: "New Castle For Investment Sports" },
  { ticker: "NCIN", nameAr: "استثمارات مدينة نيل سيتي", nameEn: "Nile City Investment" },
  { ticker: "NCGC", nameAr: "النيل لحليج الأقطان", nameEn: "Nile Cotton Ginning" },
  { ticker: "NOAF", nameAr: "شمال أفريقيا للاستثمار العقاري", nameEn: "North Africa Company For Real Estate Investment" },
  { ticker: "MILS", nameAr: "مطاحن شمال القاهرة", nameEn: "North Cairo Flour Mills" },
  { ticker: "NEDA", nameAr: "شمال الصعيد للتنمية والإنتاج الزراعي", nameEn: "North Upper Egypt Development & Agricultural Production" },
  { ticker: "NINH", nameAr: "مستشفى النزهة الدولي", nameEn: "Nozha International Hospital" },
  { ticker: "OCPH", nameAr: "أكتوبر فارما", nameEn: "October Pharma" },
  { ticker: "OCIC", nameAr: "أوراسكوم للإنشاء والصناعة", nameEn: "Orascom Construction Industries" },
  { ticker: "ODHN", nameAr: "أوراسكوم للتنمية القابضة", nameEn: "Orascom Development Holding AG" },
  { ticker: "ORHD", nameAr: "أوراسكوم للفنادق والتنمية", nameEn: "Orascom Hotels And Development" },
  { ticker: "OTMT", nameAr: "أوراسكوم للاستثمار القابضة", nameEn: "Orascom Investment Holding" },
  { ticker: "ORWE", nameAr: "النساجون الشرقيون للسجاد", nameEn: "Oriental Weavers Carpet" },
  { ticker: "EBSC", nameAr: "أسوول إي إس بي للسمسرة", nameEn: "Osool ESB Securities Brokerage" },
  { ticker: "PACH", nameAr: "الدهانات والصناعات الكيماوية", nameEn: "Paint & Chemicals Industries" },
  { ticker: "PHDC", nameAr: "بالم هيلز للتطوير", nameEn: "Palm Hills Development Company" },
  { ticker: "SIMO", nameAr: "ورق الشرق الأوسط (سيمو)", nameEn: "Paper Middle East (Simo)" },
  { ticker: "PTCC", nameAr: "فرعون تك للتحكم والاتصالات", nameEn: "Pharaoh Tech For Control And Communication Systems" },
  { ticker: "ASPI", nameAr: "أسبر كابيتال للاستثمارات المالية", nameEn: "Aspire Capital Holding For Financial Investments" },
  { ticker: "PSAD", nameAr: "بورسعيد للتنمية الزراعية والإنشاء", nameEn: "Port Said Agricultural Development and Construction" },
  { ticker: "ARAB", nameAr: "المطورون العرب القابضة", nameEn: "Arab Developers Holding" },
  { ticker: "PRMH", nameAr: "بريمير القابضة", nameEn: "Prime Holding" },
  { ticker: "PHTV", nameAr: "فنادق ومنتجعات الأهرامات", nameEn: "Pyramisa Hotels and Resorts" },
  { ticker: "QNBA", nameAr: "قطر الوطني الأهلي", nameEn: "Qatar National Bank Alahly" },
  { ticker: "RAKT", nameAr: "العامة لصناعة الورق راكتا", nameEn: "General Company for Paper Industry Rakta" },
  { ticker: "RACC", nameAr: "راية لمراكز الاتصال", nameEn: "Raya Contact Center" },
  { ticker: "RAYA", nameAr: "راية القابضة للاستثمارات المالية", nameEn: "Raya Holding for Financial Investments" },
  { ticker: "REAC", nameAr: "ريكاب للاستثمارات المالية", nameEn: "Reacap Financial Investments" },
  { ticker: "RTVC", nameAr: "ريمكو لإنشاء القرى السياحية", nameEn: "Remco For Touristic Villages Construction" },
  { ticker: "RIVA", nameAr: "ريفا فارما", nameEn: "Riva Pharma" },
  { ticker: "RMTV", nameAr: "رواد مصر للاستثمار السياحي", nameEn: "Rowad Misr Tourism Investment" },
  { ticker: "ROTO", nameAr: "رواد السياحة (الرواد)", nameEn: "Rowad Tourism (Al Rowad)" },
  { ticker: "RUBX", nameAr: "روبكس الدولية للبلاستيك والأكريليك", nameEn: "Rubex International For Plastic And Acrylic Manufacturing" },
  { ticker: "SIPC", nameAr: "صابا الدولية للأدوية والكيماويات", nameEn: "Sabaa International Company For Pharmaceutical And Chemical" },
  { ticker: "SMFR", nameAr: "صمد مصر إيجيفرت", nameEn: "Samad Misr EGYFERT" },
  { ticker: "SMCS", nameAr: "سامكريت مصر", nameEn: "Samcrete Misr" },
  { ticker: "SMCSA", nameAr: "سامكريت مصر أسهم ممتازة", nameEn: "Samcrete Misr Preferred Shares" },
  { ticker: "SEIG", nameAr: "الاستثمار والتمويل السعودي المصري", nameEn: "Saudi Egyptian Investment & Finance" },
  { ticker: "SEIGA", nameAr: "الاستثمار والتمويل السعودي المصري (دولار)", nameEn: "Saudi Egyptian Investment & Finance (Usd)" },
  { ticker: "SNFC", nameAr: "الشرقية الوطنية للأمن الغذائي", nameEn: "Sharkia National Company for Food Security" },
  { ticker: "SDTI", nameAr: "شركة شرم دريمز للاستثمار السياحي", nameEn: "Sharm Dreams Co For Tourism Investment" },
  { ticker: "SKPC", nameAr: "بتروكيماويات سيدي كرير", nameEn: "Sidi Kerir Petrochemicals" },
  { ticker: "SCEM", nameAr: "سيناء للإسمنت", nameEn: "Sinai Cement" },
  { ticker: "OCDI", nameAr: "السادس من أكتوبر للتنمية والاستثمار (سوديك)", nameEn: "Six Of October Development & Investment (Sodic)" },
  { ticker: "SLTD", nameAr: "سكاى لايت للتنمية السياحية", nameEn: "Sky Light For Tourist Development Company" },
  { ticker: "SAIB", nameAr: "المصرف العربي الدولي", nameEn: "Societe Arabe Internationale De Banque" },
  { ticker: "SNFI", nameAr: "سوهاج الوطنية للصناعات الغذائية", nameEn: "Sohag National Company For Food Industries" },
  { ticker: "SCFM", nameAr: "مطاحن ومخابز جنوب القاهرة والجيزة", nameEn: "South Cairo & Giza Mills & Bakeries" },
  { ticker: "SVCE", nameAr: "أسمنت جنوب الوادي", nameEn: "South Valley Cement" },
  { ticker: "SCTS", nameAr: "قناة السويس للتكنولوجيا والتسوية", nameEn: "Sues Canal Company For Technology Settling" },
  { ticker: "SBAG", nameAr: "أكياس السويس", nameEn: "Suez Bags" },
  { ticker: "CANA", nameAr: "بنك قناة السويس", nameEn: "Suez Canal Bank" },
  { ticker: "SUCE", nameAr: "أسمنت السويس", nameEn: "Suez Cement" },
  { ticker: "TMGH", nameAr: "طلعت مصطفى القابضة", nameEn: "TMG Holding" },
  { ticker: "TECH", nameAr: "تغليف الصناعات - مصر", nameEn: "Taghleef Industries - Egypt" },
  { ticker: "ETEL", nameAr: "المصرية للاتصالات", nameEn: "Telecom Egypt" },
  { ticker: "ADPC", nameAr: "الألبان العربية", nameEn: "The Arab Dairy Products" },
  { ticker: "TORA", nameAr: "أسمنت طرة", nameEn: "Tourah Cement" },
  { ticker: "TOUR", nameAr: "السياحة والتعمير", nameEn: "Tourism Urbanization" },
  { ticker: "TRTO", nameAr: "ترانس أوشن تورز", nameEn: "Trans Oceans Tours" },
  { ticker: "UNBE", nameAr: "البنك الاتحادي الوطني مصر", nameEn: "Union National Bank Egypt" },
  { ticker: "UASG", nameAr: "الشحن العربي المتحدة", nameEn: "United Arab Stevedoring" },
  { ticker: "UNIT", nameAr: "المتحدة للإسكان والتعمير", nameEn: "United Housing & Development" },
  { ticker: "UNIP", nameAr: "العالمية لمواد التعبئة والورق", nameEn: "Universal Company for Packaging Materials and Paper" },
  { ticker: "UNFO", nameAr: "يونيفرت للصناعات الغذائية", nameEn: "Univert Food Industries" },
  { ticker: "UEFM", nameAr: "مطاحن مصر العليا", nameEn: "Upper Egypt Flour Mills" },
  { ticker: "UTOP", nameAr: "يوتوبيا للاستثمار العقاري والسياحي", nameEn: "Utopia Real Estate Investment and Tourism" },
  { ticker: "VERT", nameAr: "فيرتيكا", nameEn: "Vertika" },
  { ticker: "VODE", nameAr: "فودافون مصر", nameEn: "Vodafone Egypt" },
  { ticker: "WKOL", nameAr: "وادي كوم أمبو لاستصلاح الأراضي", nameEn: "Wadi Kom Ombo for Land Reclamation" },
  { ticker: "XPIN", nameAr: "اكسبريس للتكامل", nameEn: "Xpress Integration" },
  { ticker: "ZMID", nameAr: "زهراء المعادي للاستثمار والتنمية", nameEn: "Zahraa Maadi Investment & Development" },
  { ticker: "DOMT", nameAr: "العربية للصناعات الغذائية (دومتي)", nameEn: "Arabian Food Industries(DOMTY)" },
  { ticker: "CLHO", nameAr: "مستشفى كليوباترا", nameEn: "Cleopatra Hospital" },
  { ticker: "OLFI", nameAr: "أرض العبور للصناعات الغذائية", nameEn: "Obour Land For Food Industries" },
  { ticker: "MTIE", nameAr: "إم إم جروب للصناعة والتجارة الدولية", nameEn: "MM Group For Industry And International Trade" },
  { ticker: "CICH", nameAr: "سي كابيتال القابضة للاستثمارات المالية", nameEn: "CI Capital Holding for Financial Investments" },
  { ticker: "CIRA", nameAr: "القاهرة للاستثمار والتنمية العقارية", nameEn: "Cairo For Investment And Real Estate Development" },
  { ticker: "CNFN", nameAr: "كونتكت المالية القابضة", nameEn: "Contact Financial Holding" },
  { ticker: "SRWA", nameAr: "صروة كابيتال", nameEn: "Sarwa Capital" },
  { ticker: "FWRY", nameAr: "فوري لتكنولوجيا البنوك والمدفوعات الإلكترونية", nameEn: "Fawry for Banking Technology and Electronic Payment" },
  { ticker: "ODIN", nameAr: "أودين للاستثمار", nameEn: "ODIN Investment" },
  { ticker: "RMDA", nameAr: "العاشر من رمضان للأدوية والمستحضرات التشخيصية - راميدا", nameEn: "Tenth of Ramadan for Pharmaceutical Industries and Diagnostic Reagents - Rameda" },
  { ticker: "AIVCB", nameAr: "الأعراف للاستثمار والاستشارات بالجنيه", nameEn: "Al Arafa Investment And Consulting in EGP" },
  { ticker: "SPMD", nameAr: "سبيد ميديكال", nameEn: "Speed Medical" },
  { ticker: "OFH", nameAr: "أوراسكوم المالية القابضة", nameEn: "Orascom Financial Holdings" },
  { ticker: "ACAMD", nameAr: "العربية لإدارة الأصول والتنمية", nameEn: "Arab Company for Asset Management And Development" },
  { ticker: "ISPH", nameAr: "ابن سينا فارما", nameEn: "Ibnsina Pharma" },
  { ticker: "TALM", nameAr: "تعليم لإدارة الخدمات", nameEn: "Taaleem Management Services" },
  { ticker: "IDHC", nameAr: "المتكاملة للتشخيص القابضة", nameEn: "Integrated Diagnostics Holdings" },
  { ticker: "ISMQ", nameAr: "الحديد والصلب للمناجم والمحاجر", nameEn: "Iron and Steel for Mines and Quarries" },
  { ticker: "TANM", nameAr: "تنمية للاستثمار العقاري", nameEn: "Tanmiya for Real Estate Investment" },
  { ticker: "EFIH", nameAr: "إي-فاينانس للاستثمارات الرقمية والمالية", nameEn: "E-finance For Digital and Financial Investments" },
  { ticker: "GDWA", nameAr: "جدوى للتنمية الصناعية", nameEn: "Gadwa For Industrial Development" },
  { ticker: "PRDC", nameAr: "رواد الخصائص للتنمية العمرانية", nameEn: "Pioneers Properties For Urban Development" },
  { ticker: "KRDI", nameAr: "نهر الخير للتنمية والاستثمار الزراعي", nameEn: "Al Khair River For Development Agricultural Investment" },
  { ticker: "MCRO", nameAr: "ماكرو جروب للأدوية", nameEn: "Macro Group Pharmaceuticals" },
  { ticker: "ODID", nameAr: "أودين للاستثمار والتنمية", nameEn: "Odin for Investment & Development" },
];

// ── Company descriptions ──────────────────────────────────────────────────────
// Covers major EGX-listed companies. Remaining companies show a default fallback.
const EGX_DESCRIPTIONS: Record<string, { ar: string; en: string }> = {
  // Banks
  COMI: { ar: "أكبر بنك خاص في مصر، تأسس عام 1975 ويقدم خدمات مصرفية شاملة للأفراد والشركات والمؤسسات.", en: "Egypt's largest private-sector bank, founded in 1975, providing comprehensive banking services to individuals and corporates." },
  CIEB: { ar: "بنك فرنسي-مصري مشترك تابع لمجموعة كريدي أجريكول الفرنسية، يقدم خدمات مصرفية متنوعة للأفراد والشركات في مصر.", en: "A French-Egyptian joint-venture bank affiliated with Crédit Agricole Group, offering retail and corporate banking in Egypt." },
  ADIB: { ar: "بنك إسلامي يقدم خدمات مصرفية متوافقة مع أحكام الشريعة الإسلامية، تابع لمجموعة بنك أبوظبي الإسلامي.", en: "An Islamic bank providing Sharia-compliant banking services in Egypt, part of Abu Dhabi Islamic Bank Group." },
  SAUD: { ar: "بنك إسلامي متخصص في الخدمات المصرفية المتوافقة مع الشريعة الإسلامية، يتبع مجموعة البركة المصرفية الدولية.", en: "An Islamic bank specializing in Sharia-compliant financial services, part of Al Baraka Banking Group." },
  EGBE: { ar: "بنك مصري-خليجي يقدم خدمات مصرفية شاملة للأفراد والشركات في مصر، مع تركيز على تسهيل الأعمال بين مصر ودول الخليج.", en: "An Egyptian-Gulf bank offering retail and corporate banking, focused on facilitating business between Egypt and the Gulf." },
  FAIT: { ar: "أول بنك إسلامي في مصر، تأسس عام 1977 ويقدم خدمات مصرفية متوافقة مع أحكام الشريعة الإسلامية.", en: "Egypt's first Islamic bank, founded in 1977, offering Sharia-compliant banking products and services." },
  FAITA: { ar: "أول بنك إسلامي في مصر (حسابات بالدولار)، تأسس عام 1977 ويقدم خدمات مصرفية متوافقة مع أحكام الشريعة.", en: "Egypt's first Islamic bank (USD accounts), founded in 1977, offering Sharia-compliant banking services." },
  HDBK: { ar: "بنك حكومي متخصص في تمويل الإسكان وقطاع التعمير، يقدم خدمات مصرفية للأفراد والمطورين العقاريين.", en: "A government bank specialized in housing and construction finance, serving individuals and real-estate developers." },
  EXPA: { ar: "بنك حكومي مصري متخصص في دعم الصادرات وتمويل المصدرين المصريين، يلعب دوراً محورياً في تنمية التجارة الخارجية.", en: "A state-owned bank specialized in supporting Egyptian exporters and financing foreign-trade operations." },
  CANA: { ar: "بنك تجاري مصري يقدم خدمات مصرفية شاملة للأفراد والشركات، ويُركز على تمويل المشروعات الصغيرة والمتوسطة.", en: "An Egyptian commercial bank offering comprehensive banking services with a focus on SME financing." },
  QNBA: { ar: "أحد أكبر البنوك في مصر، تابع لمجموعة بنك قطر الوطني (QNB)، يقدم خدمات مصرفية متكاملة للأفراد والشركات.", en: "One of Egypt's largest banks, part of QNB Group, offering integrated banking services to retail and corporate clients." },
  NBKE: { ar: "فرع بنك الكويت الوطني في مصر، يقدم خدمات مصرفية شاملة ويُعد من البنوك الكبرى في السوق المصري.", en: "The Egyptian arm of National Bank of Kuwait, offering comprehensive banking services and ranked among Egypt's top banks." },
  SAIB: { ar: "بنك دولي متخصص في تمويل التجارة الخارجية وخدمات الشركات الكبرى، يتميز بشبكة علاقات عربية ودولية واسعة.", en: "An international bank specializing in trade finance and corporate services, with extensive Arab and global relationships." },
  UNBE: { ar: "فرع البنك الاتحادي الوطني الإماراتي في مصر، يقدم حلولاً مصرفية متنوعة للأفراد والشركات.", en: "The Egyptian branch of UAE's Union National Bank, offering diverse banking solutions for retail and corporate clients." },

  // Telecoms
  ETEL: { ar: "الشركة الوطنية للاتصالات في مصر ومشغل البنية التحتية للإنترنت الثابت والكابلات البحرية، تأسست عام 1854 وتمتلك أكبر شبكة ألياف ضوئية في مصر.", en: "Egypt's national telecoms operator and fixed-line infrastructure owner, founded in 1854, operating the country's largest fibre-optic network." },
  OREG: { ar: "شركة اتصالات رائدة في مصر تقدم خدمات الهاتف المحمول والإنترنت للأفراد والشركات بقاعدة عملاء تجاوزت 40 مليون مشترك.", en: "A leading Egyptian telecom company providing mobile and internet services to over 40 million subscribers." },
  VODE: { ar: "إحدى كبرى شركات الاتصالات في مصر، تتبع مجموعة فودافون العالمية وتقدم خدمات الهاتف المحمول والإنترنت والدفع الإلكتروني.", en: "One of Egypt's top telecom operators, part of Vodafone Group, providing mobile, internet and e-payment services." },
  GTHE: { ar: "شركة اتصالات دولية تعمل في أفريقيا وآسيا وأوروبا، ومن كبرى شركات الاتصالات في الأسواق الناشئة.", en: "An international telecom company operating across Africa, Asia and Europe, and among the largest in emerging markets." },

  // Real Estate
  TMGH: { ar: "أكبر شركة تطوير عقاري في مصر والشرق الأوسط، تطور مشروع مدينتي (أكبر مشروع عقاري في المنطقة) ومجمعات سكنية ضخمة في القاهرة الجديدة.", en: "The largest real-estate developer in Egypt and the Middle East, developing Madinaty (the region's largest project) and major communities in New Cairo." },
  PHDC: { ar: "شركة تطوير عقاري رائدة متخصصة في المجتمعات السكنية الفاخرة والمتكاملة في القاهرة الجديدة وأكتوبر والساحل الشمالي.", en: "A leading real-estate developer specializing in premium integrated residential communities in New Cairo, October City and the North Coast." },
  OCDI: { ar: "شركة تطوير عقاري راقية تُركز على مجتمعات السكن الفاخر (سوديك)، تمتلك مشروعات في أكتوبر والقاهرة الجديدة.", en: "A premium real-estate developer focused on upscale residential communities (SODIC), with projects in October City and New Cairo." },
  EMFD: { ar: "شركة تطوير عقاري مصرية-إماراتية تابعة لمجموعة إعمار الإماراتية، تطور مشروعات ميفيدا وأبراج مميزة في القاهرة الجديدة.", en: "An Egyptian-UAE real-estate developer, a subsidiary of Emaar Properties, developing Mivida and landmark projects in New Cairo." },
  MNHD: { ar: "شركة حكومية تتولى تطوير وبيع الأراضي والوحدات السكنية في مدينة نصر، ومن أقدم شركات التطوير العقاري في مصر.", en: "A state-owned developer managing land and residential-unit sales in Nasr City, one of Egypt's oldest real-estate companies." },
  HELI: { ar: "شركة متخصصة في تطوير الإسكان والمجمعات العمرانية في منطقة مصر الجديدة (هليوبوليس)، إحدى أعرق مناطق القاهرة.", en: "A company specializing in housing and urban development in the Heliopolis district, one of Cairo's most historic areas." },
  ARAB: { ar: "شركة قابضة عقارية تمتلك محفظة متنوعة من المشروعات السكنية والتجارية في مصر.", en: "A real-estate holding company with a diversified portfolio of residential and commercial projects across Egypt." },

  // Fertilizers & Chemicals
  ABUK: { ar: "من أكبر منتجي الأسمدة النيتروجينية في الشرق الأوسط، تنتج الأمونيا واليوريا ويقع مصنعها الرئيسي في أبو قير بالإسكندرية.", en: "One of the Middle East's largest nitrogen-fertilizer producers, manufacturing ammonia and urea from its Abu Qir plant in Alexandria." },
  MFPC: { ar: "مصنع ضخم لإنتاج الأسمدة النيتروجينية في دمياط (موبكو)، يُنتج اليوريا والأمونيا للاستهلاك المحلي والتصدير.", en: "A large nitrogen-fertilizer complex at Damietta (MOPCO) producing urea and ammonia for domestic use and export." },
  SMFR: { ar: "شركة مصنعة للأسمدة النيتروجينية تعتمد على الغاز الطبيعي كمدخل أساسي، وتُسهم في تلبية احتياجات السوق المحلي.", en: "A nitrogen-fertilizer producer that uses natural gas as its primary feedstock, contributing to Egypt's domestic supply." },
  EGCH: { ar: "مصنع حيوي في أسوان يُنتج الأسمدة النيتروجينية والكيماويات (كيما) باستخدام الطاقة الكهرومائية من السد العالي.", en: "A key industrial plant in Aswan (Kima) producing nitrogen fertilizers and chemicals powered by Aswan High Dam hydroelectricity." },
  SKPC: { ar: "شركة متخصصة في إنتاج البتروكيماويات وبخاصة البولي إيثيلين، تقع في سيدي كرير على ساحل البحر المتوسط.", en: "A petrochemicals company specializing in polyethylene production, located on the Mediterranean coast at Sidi Kerir." },

  // Steel & Heavy Industry
  ESRS: { ar: "أكبر منتج للصلب في مصر وأحد أبرز المنتجين في منطقة الشرق الأوسط، يُسيطر على الجزء الأكبر من سوق حديد التسليح المحلي.", en: "Egypt's largest steel producer and one of the region's biggest, dominating the domestic rebar market." },
  IRAX: { ar: "مصنع كبير للحديد والصلب في الإسكندرية (العز الدخيلة)، يُنتج حديد التسليح وشرائح الصلب للسوق المحلي والتصدير.", en: "A large steel mill in Alexandria (El Dekheila) producing rebar and steel sections for domestic and export markets." },
  SWDY: { ar: "شركة عالمية رائدة في صناعة الكابلات الكهربائية وأنظمة نقل الطاقة، تعمل في أكثر من 40 دولة وتُعد من أكبر منتجي الكابلات في العالم.", en: "A global leader in electrical cables and energy-transmission systems, operating in 40+ countries and one of the world's top cable manufacturers." },
  EGAL: { ar: "الشركة الحكومية المنتجة للألومنيوم في مصر، تقع في نجع حمادي وتعتمد على الطاقة الكهرومائية من السد العالي في عملياتها.", en: "Egypt's state-owned aluminium producer, located in Nag Hammadi and powered by hydroelectric energy from the Aswan High Dam." },

  // Finance & Investment
  HRHO: { ar: "أكبر بنك استثماري وشركة خدمات مالية في منطقة الأسواق الناشئة والحدودية بالشرق الأوسط وأفريقيا (EFG Hermes)، تقدم خدمات إدارة الأصول والوساطة والاكتتابات.", en: "The largest investment bank and financial-services firm in MENA/frontier markets (EFG Hermes), offering asset management, brokerage and capital-markets services." },
  FWRY: { ar: "الشركة الرائدة في مجال الدفع الإلكتروني ومدفوعات الفواتير في مصر، تُعالج مئات الملايين من المعاملات سنوياً عبر شبكتها الواسعة.", en: "Egypt's leading e-payment and bill-payment company, processing hundreds of millions of transactions annually across its extensive network." },
  EFIH: { ar: "منصة الدفع الرقمي الحكومية في مصر (إي-فاينانس)، تُشغّل منظومة مدفوعات الحكومة الإلكترونية وخدمات التحصيل الرقمي للدولة.", en: "Egypt's government digital-payment platform (e-Finance), operating the state's electronic payment and collection infrastructure." },
  CNFN: { ar: "شركة خدمات مالية متكاملة رائدة في التمويل الاستهلاكي والتأجير التمويلي وإدارة المدفوعات في مصر.", en: "A leading integrated financial-services company specializing in consumer finance, leasing and payments management in Egypt." },
  CICH: { ar: "مجموعة خدمات مالية متكاملة تضم CI Capital لبنك الاستثمار ومنصات متنوعة للتمويل الاستهلاكي.", en: "An integrated financial-services group comprising CI Capital investment banking and various consumer-finance platforms." },
  SRWA: { ar: "شركة مالية متخصصة في التمويل الاستهلاكي والتأجير التمويلي وإدارة الأصول في مصر.", en: "A financial company specializing in consumer finance, leasing and asset management in Egypt." },
  BTFH: { ar: "شركة خدمات مالية متخصصة في إدارة الأصول والوساطة المالية وبنك الاستثمار في مصر والمنطقة.", en: "A financial-services company specializing in asset management, brokerage and investment banking in Egypt and the region." },
  CCAP: { ar: "شركة قابضة متنوعة تستثمر في قطاعات الطاقة والبنية التحتية والإعلام واللوجستيات عبر محفظة واسعة من الشركات التابعة.", en: "A diversified holding company investing in energy, infrastructure, media and logistics through a wide portfolio of subsidiaries." },
  OFH: { ar: "الذراع المالية لمجموعة أوراسكوم، تُركز على الاستثمار في الخدمات المالية في مصر ومنطقة الشرق الأوسط وأفريقيا.", en: "The financial arm of Orascom Group, focused on investing in financial services across Egypt, MENA and Africa." },
  EKHO: { ar: "شركة قابضة مصرية-كويتية متنوعة تستثمر في قطاعات البتروكيماويات والتأمين والخدمات المالية في مصر.", en: "An Egyptian-Kuwaiti diversified holding company investing in petrochemicals, insurance and financial services in Egypt." },

  // Healthcare
  CLHO: { ar: "سلسلة مستشفيات خاصة رائدة في مصر، تضم عدة مستشفيات في القاهرة وتقدم خدمات صحية شاملة عبر طاقم طبي متخصص.", en: "A leading private hospital chain in Egypt comprising multiple Cairo hospitals and offering comprehensive healthcare services." },
  IDHC: { ar: "أكبر مجموعة مختبرات تشخيصية طبية في مصر والشرق الأوسط، تمتلك شبكة واسعة من مختبرات التحاليل الطبية (IDH).", en: "The largest medical-diagnostic laboratory group in Egypt and the Middle East, operating a broad IDH laboratory network." },
  ISPH: { ar: "أكبر موزع دوائي في مصر (ابن سينا فارما)، يربط شركات الأدوية بأكثر من 60,000 صيدلية ومستشفى على مستوى الجمهورية.", en: "Egypt's largest pharmaceutical distributor (Ibnsina Pharma), linking drug manufacturers to over 60,000 pharmacies and hospitals nationwide." },
  RMDA: { ar: "شركة أدوية مصرية رائدة متخصصة في إنتاج الأدوية الجنيسة عالية الجودة والكواشف التشخيصية (راميدا).", en: "A leading Egyptian pharmaceutical company specialized in high-quality generics and diagnostic reagents (Rameda)." },
  MIPH: { ar: "شركة أدوية متخصصة في تطوير وتصنيع الأدوية الحيوية والبروتينات الطبية لعلاج الأمراض المزمنة.", en: "A pharmaceutical company specializing in developing and manufacturing biopharmaceuticals and medical proteins for chronic diseases." },
  MCRO: { ar: "شركة قابضة دوائية متنوعة تعمل في توزيع وتصنيع الأدوية في مصر والأسواق الإقليمية.", en: "A diversified pharmaceutical holding company engaged in drug distribution and manufacturing in Egypt and regional markets." },
  SPMD: { ar: "شركة رائدة في تقديم خدمات التحاليل الطبية وإدارة المعامل، تمتلك شبكة من مراكز التحاليل في مصر.", en: "A leading medical-laboratory services company, operating a network of testing centers across Egypt." },
  NINH: { ar: "مستشفى دولي متخصص في تقديم خدمات الرعاية الصحية المتقدمة في منطقة النزهة بالقاهرة.", en: "An international hospital providing advanced healthcare services in the Nozha area of Cairo." },

  // Education
  TALM: { ar: "شركة رائدة في إدارة المدارس الخاصة والدولية في مصر، تُشغّل مجموعة من المدارس ذات المناهج الدولية وتخدم آلاف الطلاب.", en: "A leading operator of private and international schools in Egypt, running internationally-accredited campuses serving thousands of students." },
  MOED: { ar: "شركة متخصصة في تقديم خدمات وحلول التعليم الحديث، تمتلك شبكة من المدارس والمراكز التعليمية في مصر.", en: "A company specializing in modern educational services and solutions, operating a network of schools and learning centers in Egypt." },
  CIRA: { ar: "شركة قابضة متنوعة في قطاع التعليم والتطوير العقاري في مصر، تمتلك مؤسسات تعليمية مرموقة.", en: "A diversified holding company in education and real-estate development in Egypt, owning prestigious educational institutions." },

  // Food & Consumer
  JUFO: { ar: "أكبر شركة لإنتاج الألبان والعصائر في مصر، تمتلك ماركة جهينة الشهيرة في الألبان والعصائر والمنتجات الغذائية المتنوعة.", en: "Egypt's largest dairy and juice producer, owning the iconic Juhayna brand across dairy, juice and diverse food products." },
  EFID: { ar: "شركة رائدة في صناعة الحلوى والمخبوزات المعلبة في مصر والشرق الأوسط، تمتلك ماركات شهيرة مثل هوهوز وتايكي وكريمي.", en: "A leading packaged-snack and baked-goods company in Egypt and the MENA region, owning popular brands like HoHos, Twinkies and Creemy." },
  DOMT: { ar: "أكبر منتج للجبن المعالج في مصر (دومتي)، يمتلك حصة سوقية كبيرة في قطاع الألبان ويُصدّر منتجاته إلى أكثر من 25 دولة.", en: "Egypt's largest processed-cheese producer (Domty) with a dominant dairy market share, exporting to over 25 countries." },
  OLFI: { ar: "شركة متنوعة في الصناعات الغذائية تُنتج مجموعة واسعة من منتجات الألبان والأجبان والأغذية المصنعة من مدينة العبور الصناعية.", en: "A diversified food-industry company producing a wide range of dairy, cheese and processed-food products from its Obour industrial base." },
  EAST: { ar: "شركة حكومية تحتكر إنتاج وتوزيع السجائر والتبغ في مصر، وتُعد من أكبر الشركات من حيث الإيرادات والأرباح في البورصة المصرية.", en: "A state-owned monopoly producing and distributing cigarettes and tobacco in Egypt, one of the highest-earning companies on the EGX." },
  ADPC: { ar: "شركة مصرية منتجة لمجموعة متنوعة من منتجات الألبان والأجبان العربية.", en: "An Egyptian company producing a diverse range of Arab-style dairy products and cheeses." },

  // Autos
  AUTO: { ar: "أكبر موزع للسيارات في مصر ومنطقة الشرق الأوسط وأفريقيا (جي بي أوتو)، يمثل علامات تجارية عالمية كبرى كهيونداي وشيري وغيرها.", en: "The largest vehicle distributor in Egypt, MENA and Africa (GB Auto), representing major global brands including Hyundai and Chery." },

  // Construction & Engineering
  OCIC: { ar: "شركة مقاولات عالمية رائدة (أوراسكوم للإنشاء)، تُنفذ مشاريع البنية التحتية والطاقة والصناعة في أمريكا الشمالية والشرق الأوسط وأفريقيا وأوروبا.", en: "A leading global contractor (Orascom Construction) executing infrastructure, energy and industrial projects across North America, MENA, Africa and Europe." },

  // Media & Tech
  MPRC: { ar: "أكبر مجمع للإنتاج الإعلامي في منطقة الشرق الأوسط وأفريقيا، يضم استوديوهات تلفزيونية وسينمائية وبنية تحتية متكاملة للإنتاج الإعلامي.", en: "The largest media production complex in MENA and Africa, housing TV and film studios with full production infrastructure." },
  RAYA: { ar: "مجموعة قابضة متنوعة تعمل في قطاعات تكنولوجيا المعلومات والاتصالات والتعليم وتوزيع المعدات والخدمات اللوجستية.", en: "A diversified holding group operating in IT, telecoms, education, equipment distribution and logistics." },
  RACC: { ar: "شركة رائدة في مجال مراكز الاتصال وإدارة تجربة العملاء في مصر والمنطقة، تُقدم خدمات الـ outsourcing لكبرى الشركات العالمية.", en: "A leading contact-centre and customer-experience management company in Egypt, providing outsourcing services to major global firms." },
  EGSA: { ar: "تُشغّل منظومة الأقمار الصناعية المصرية (نايل سات) التي تبث مئات القنوات التلفزيونية لمنطقة الشرق الأوسط وشمال أفريقيا وأوروبا.", en: "Operates Egypt's NileSat satellite system, broadcasting hundreds of TV channels across MENA and Europe." },

  // Textiles
  ORWE: { ar: "أكبر منتج للسجاد في العالم (النساجون الشرقيون)، يُصدّر إلى أكثر من 130 دولة ويُسيطر على حصة سوقية عالمية كبيرة.", en: "The world's largest carpet manufacturer (Oriental Weavers), exporting to over 130 countries and holding a major global market share." },

  // Cement
  ARCC: { ar: "من أكبر منتجي الأسمنت في مصر (الأسمنت العربية)، تمتلك طاقة إنتاجية كبيرة وتُصدّر جزءاً من إنتاجها.", en: "One of Egypt's largest cement producers (Arabian Cement), with substantial production capacity and some export activity." },
  SUCE: { ar: "من أبرز شركات الأسمنت في مصر، تمتلك مصانع في السويس وتُعد من أوائل شركات الأسمنت تأسيساً في مصر.", en: "One of Egypt's most prominent cement companies with plants in Suez, and one of the earliest cement producers in the country." },
  ALEXA: { ar: "مصنع أسمنت رائد في الإسكندرية، من أوائل شركات الأسمنت في مصر ويخدم أسواق شمال مصر والتصدير.", en: "A leading cement plant in Alexandria, one of Egypt's pioneer cement producers serving northern Egypt and export markets." },
  SVCE: { ar: "شركة أسمنت تعمل في منطقة جنوب الوادي بالصعيد، وتُعد رافداً مهماً للبنية التحتية في جنوب مصر.", en: "A cement company operating in South Valley (Upper Egypt), a key infrastructure supplier for southern Egypt." },
  TORA: { ar: "مصنع أسمنت عريق يقع في منطقة طرة جنوب القاهرة، من أقدم وأعرق مصانع الأسمنت في مصر.", en: "A historic cement plant in Tourah south of Cairo, one of Egypt's oldest and most established cement factories." },
  SCEM: { ar: "شركة أسمنت تعمل في شبه جزيرة سيناء، تستفيد من الموقع الاستراتيجي للمواد الخام في المنطقة.", en: "A cement company operating in Sinai, benefiting from the region's strategic raw-material resources." },

  // Oil & Gas
  EGAS: { ar: "الشركة الحكومية المتخصصة في توزيع الغاز الطبيعي للمنازل والمصانع والشركات في مختلف محافظات مصر.", en: "The state-owned company specializing in natural gas distribution to homes, factories and businesses across Egypt." },
  MOIL: { ar: "شركة متخصصة في خدمات الحفر البحري ودعم عمليات إنتاج النفط والغاز في البحر الأحمر وشمال أفريقيا.", en: "A company specialized in offshore drilling and oil-and-gas production support services in the Red Sea and North Africa." },

  // Orascom Group
  ODHN: { ar: "شركة سياحية-عقارية كبرى مدرجة في بورصتي مصر وسويسرا، تمتلك مشروعات ضخمة في مصر والمغرب والأردن وسويسرا وعُمان.", en: "A major tourism-real estate developer listed in Egypt and Switzerland, with mega-projects in Egypt, Morocco, Jordan, Switzerland and Oman." },
  OTMT: { ar: "الشركة القابضة لمجموعة أوراسكوم للاستثمار، تمتلك محفظة متنوعة من الاستثمارات في قطاعات الطاقة والإنشاء والسياحة.", en: "Orascom Investment Holding, controlling a diversified portfolio across energy, construction and tourism sectors." },
  ORHD: { ar: "شركة متخصصة في تطوير الفنادق والمنتجعات السياحية والمشروعات العقارية في مصر والخارج.", en: "A company specialized in developing hotels, tourist resorts and real-estate projects in Egypt and abroad." },

  // Pharma (additional)
  PHAR: { ar: "شركة دوائية مصرية متكاملة تعمل في تصنيع وتسويق الأدوية البشرية والبيطرية في مصر والأسواق الإقليمية.", en: "An integrated Egyptian pharmaceutical company manufacturing and marketing human and veterinary medicines in Egypt and regional markets." },
  AXPH: { ar: "شركة دوائية راسخة في الإسكندرية تُنتج مجموعة متنوعة من المستحضرات الدوائية والكيماوية.", en: "An established Alexandria-based pharmaceutical company producing a diverse range of medicinal and chemical preparations." },

  // Flour Mills
  AFMC: { ar: "شركة طحن وإنتاج الدقيق في الإسكندرية، تُزود السوق المحلي بالدقيق والمنتجات المطحونة.", en: "An Alexandria-based flour milling company supplying the domestic market with flour and milled products." },
  EDFM: { ar: "شركة مطاحن تعمل في شرق الدلتا المصرية، تُنتج الدقيق والردة وتُسهم في سلسلة الغذاء الوطنية.", en: "A flour-milling company in the eastern Nile Delta, producing flour and bran and contributing to the national food chain." },
  MILS: { ar: "شركة مطاحن تعمل في منطقة شمال القاهرة، وتُعد من الروافد الأساسية لإمداد العاصمة بالدقيق.", en: "A flour-milling company in north Cairo, one of the primary suppliers of flour to the Egyptian capital." },
  WCDF: { ar: "شركة مطاحن تخدم أسواق وسط وغرب الدلتا المصرية بمنتجات الدقيق والحبوب.", en: "A flour-milling company serving the central and western Nile Delta markets with flour and grain products." },
};

export function getStockName(ticker: string, lang: "ar" | "en" = "ar"): string {
  const stock = EGX_STOCKS.find((s) => s.ticker.toUpperCase() === ticker.toUpperCase());
  if (!stock) return ticker;
  return lang === "ar" ? stock.nameAr : stock.nameEn;
}

export function getStockInfo(ticker: string): EGXStock | undefined {
  const stock = EGX_STOCKS.find((s) => s.ticker.toUpperCase() === ticker.toUpperCase());
  if (!stock) return undefined;
  const desc = EGX_DESCRIPTIONS[ticker.toUpperCase()];
  if (!desc) return stock;
  return { ...stock, descriptionAr: desc.ar, descriptionEn: desc.en };
}

export function searchStocks(query: string, lang: "ar" | "en" = "ar"): EGXStock[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const qTrim = query.trim();
  return EGX_STOCKS.filter(
    (s) =>
      s.ticker.toLowerCase().includes(q) ||
      (qTrim && s.nameAr.includes(qTrim)) ||
      s.nameEn.toLowerCase().includes(q)
  );
}
