// EGX Stocks — copied from web src/lib/egxStocks.ts
export interface EGXStock {
  ticker: string;
  nameAr: string;
  nameEn: string;
}

export const EGX_STOCKS: EGXStock[] = [
  { ticker: "ABUK", nameAr: "أبو قير للأسمدة", nameEn: "Abu Qir Fertilizers" },
  { ticker: "ADIB", nameAr: "بنك أبوظبي الإسلامي مصر", nameEn: "Abu Dhabi Islamic Bank Egypt" },
  { ticker: "ACRO", nameAr: "أكرو مصر", nameEn: "Acrow Misr" },
  { ticker: "APPC", nameAr: "التعبئة الدوائية المتقدمة", nameEn: "Advanced Pharmaceutical Packaging Co." },
  { ticker: "AJWA", nameAr: "عجوة للصناعات الغذائية", nameEn: "Ajwa For Food Industries Company Egypt" },
  { ticker: "SAUD", nameAr: "بنك البركة مصر", nameEn: "Al Baraka Bank Egypt" },
  { ticker: "FNAR", nameAr: "الفنار للمقاولات والتجارة", nameEn: "Al Fanar Contracting, Construction, Trade, Import And Export" },
  { ticker: "AMPI", nameAr: "المعاصر للبرمجة ونشر المعلومات", nameEn: "Al Moasher For Programming And Information Dissemination" },
  { ticker: "ATLC", nameAr: "التوفيق للتأجير التمويلي", nameEn: "Al Tawfeek Leasing Company - A.T.Lease" },
  { ticker: "ALEXA", nameAr: "أسمنت الإسكندرية", nameEn: "Alexandria Cement" },
  { ticker: "ALCN", nameAr: "الإسكندرية للحاويات والبضائع", nameEn: "Alexandria Containers And Goods" },
  { ticker: "AFMC", nameAr: "مطاحن الإسكندرية", nameEn: "Alexandria Flour Mills" },
  { ticker: "AMOC", nameAr: "الإسكندرية للزيوت المعدنية", nameEn: "Alexandria Mineral Oils Company" },
  { ticker: "ANFI", nameAr: "الإسكندرية الوطنية للاستثمارات المالية", nameEn: "Alexandria National Company For Financial Investments" },
  { ticker: "AMES", nameAr: "المركز الطبي الجديد بالإسكندرية", nameEn: "Alexandria New Medical Center" },
  { ticker: "AXPH", nameAr: "الإسكندرية للأدوية والصناعات الكيماوية", nameEn: "Alexandria Co for Pharmaceutical and Chemical Industries" },
  { ticker: "SPIN", nameAr: "الإسكندرية للغزل والنسيج", nameEn: "Alexandria Spinning & Weaving (SPINALEX)" },
  { ticker: "AMEC", nameAr: "أميكو للصناعات الطبية", nameEn: "Ameco Medical Industries" },
  { ticker: "AMER", nameAr: "أمير جروب القابضة", nameEn: "Amer Group Holding" },
  { ticker: "ALUM", nameAr: "العربية للألومنيوم", nameEn: "Arab Aluminum" },
  { ticker: "CERA", nameAr: "السيراميك العربي", nameEn: "Arab Ceramic" },
  { ticker: "ACGC", nameAr: "العربية لحليج الأقطان", nameEn: "Arab Cotton Ginning" },
  { ticker: "AMIA", nameAr: "العرب للملتقى الاستثماري", nameEn: "Arab Moltaka Investments Co." },
  { ticker: "ADCI", nameAr: "العربية للأدوية والصناعات الكيماوية", nameEn: "Arab Drug Company for Pharmaceuticals and Chemical" },
  { ticker: "APSW", nameAr: "العربية للغزل والنسيج بولفارا", nameEn: "Arab Polvara Spinning And Weaving" },
  { ticker: "RREI", nameAr: "العربية للاستثمار العقاري", nameEn: "Arab Real Estate Investment Co." },
  { ticker: "ARVA", nameAr: "العربية للصمامات", nameEn: "Arab Valves Company" },
  { ticker: "AIND", nameAr: "استثمارات العربية للتنمية", nameEn: "Arabia Investments Development Financial Investments Holding" },
  { ticker: "ARCC", nameAr: "الأسمنت العربية", nameEn: "Arabian Cement Company" },
  { ticker: "ASCM", nameAr: "أسيك للتعدين", nameEn: "Asek Company For Mining - Ascom" },
  { ticker: "AITG", nameAr: "أسيوط الإسلامية للتجارة والتنمية", nameEn: "Assiut Islamic National Trade and Development" },
  { ticker: "ALRA", nameAr: "أطلس لاستصلاح الأراضي", nameEn: "Atlas For Land Reclamation And Agricultural Processing" },
  { ticker: "BIGP", nameAr: "المجموعة الاستثمارية البربرية", nameEn: "El Barbary Investment Group (BIG)" },
  { ticker: "BTFH", nameAr: "بلتون المالية القابضة", nameEn: "Beltone Financial Holding" },
  { ticker: "BCAP", nameAr: "بلتون كابيتال للاستثمارات المالية", nameEn: "Beltone Capital Holding For Financial Investments" },
  { ticker: "BSFR", nameAr: "التضامن للإسكان والأمن الغذائي", nameEn: "Brothers Solidarity For Real Estate Investment And Food Security" },
  { ticker: "CIRF", nameAr: "القاهرة للتنمية والاستثمار", nameEn: "Cairo Development and Investment" },
  { ticker: "CAED", nameAr: "القاهرة للخدمات التعليمية", nameEn: "Cairo Educational Services" },
  { ticker: "COSG", nameAr: "القاهرة للزيوت والصابون", nameEn: "Cairo Oils & Soap" },
  { ticker: "CPCI", nameAr: "القاهرة للأدوية والصناعات الكيماوية", nameEn: "Cairo Pharmaceuticals and Chemical Industries" },
  { ticker: "POUL", nameAr: "القاهرة للدواجن", nameEn: "Cairo Poultry" },
  { ticker: "CSAG", nameAr: "وكالات قناة السويس للملاحة", nameEn: "Canal Shipping Agencies" },
  { ticker: "PRCL", nameAr: "السيراميك والبورسلين", nameEn: "Ceramic & Porcelain" },
  { ticker: "CCAP", nameAr: "قلعة القابضة", nameEn: "Qalaa Holdings" },
  { ticker: "CCAPP", nameAr: "قلعة القابضة - أسهم ممتازة", nameEn: "Qalaa Holdings - Preferred Shares" },
  { ticker: "COMI", nameAr: "البنك التجاري الدولي", nameEn: "Commercial International Bank (Egypt)" },
  { ticker: "CIEB", nameAr: "كريدي أجريكول مصر", nameEn: "Credit Agricole Egypt" },
  { ticker: "DCRC", nameAr: "دلتا للإنشاء وإعادة الإعمار", nameEn: "Delta Construction & Rebuilding" },
  { ticker: "DTPP", nameAr: "دلتا للطباعة والتغليف", nameEn: "Delta Co for Printing and Packaging" },
  { ticker: "DEIN", nameAr: "دلتا للتأمين", nameEn: "Delta Insurance" },
  { ticker: "SUGR", nameAr: "دلتا للسكر", nameEn: "Delta Sugar" },
  { ticker: "DAPH", nameAr: "الدلتا للاستشارات الهندسية", nameEn: "Development & Engineering Consultants" },
  { ticker: "DSCW", nameAr: "دايس للملابس الرياضية وال casual", nameEn: "Dice Sport & Casual Wear" },
  { ticker: "EDFM", nameAr: "مطاحن شرق الدلتا", nameEn: "East Delta Flour Mills" },
  { ticker: "EAST", nameAr: "الشرقية للدخان", nameEn: "Eastern Tobacco" },
  { ticker: "EFID", nameAr: "إديتا للصناعات الغذائية", nameEn: "Edita Food Industries" },
  { ticker: "HRHO", nameAr: "هيرمس القابضة", nameEn: "EFG Hermes Holding Company" },
  { ticker: "EGX30ETF", nameAr: "صندوق مؤشر EGX 30", nameEn: "Egx 30 Index Etf" },
  { ticker: "EGAL", nameAr: "مصر للألومنيوم", nameEn: "Egypt Aluminum Company" },
  { ticker: "EPCO", nameAr: "مصر للدواجن", nameEn: "Egypt For Poultry" },
  { ticker: "MISR", nameAr: "مصر القارية للجرانيت والرخام", nameEn: "Egypt Intercontinental for Granite and Marble" },
  { ticker: "ESAC", nameAr: "مصر جنوب أفريقيا للاتصالات", nameEn: "Egypt-South Africa For Communication" },
  { ticker: "EASB", nameAr: "المصرية العربية ثمار للسمسرة", nameEn: "Egyptian Arabian Company Themar for Securities Brokerage" },
  { ticker: "EGCH", nameAr: "الشركة المصرية للصناعات الكيماوية (كيما)", nameEn: "Egyptian Chemical Industries (Kima)" },
  { ticker: "OREG", nameAr: "أورنج مصر للاتصالات", nameEn: "Orange Egypt for Telecommunications" },
  { ticker: "EFIC", nameAr: "المصرية المالية والصناعية", nameEn: "Egyptian Financial & Industrial" },
  { ticker: "EDBM", nameAr: "المصرية لتطوير مواد البناء", nameEn: "Egyptian For Developing Building Materials" },
  { ticker: "EGTS", nameAr: "المصرية للمنتجعات السياحية", nameEn: "Egyptian For Tourism Resorts" },
  { ticker: "EGBE", nameAr: "البنك المصري الخليجي", nameEn: "Egyptian Gulf Bank" },
  { ticker: "PHAR", nameAr: "المصرية الدولية للأدوية", nameEn: "Egyptian International Pharmaceuticals Industries" },
  { ticker: "EITP", nameAr: "المصرية للمشروعات السياحية الدولية", nameEn: "Egyptian Company for International Touristic Projects" },
  { ticker: "IRON", nameAr: "المصرية للحديد والصلب", nameEn: "Egyptian Iron & Steel" },
  { ticker: "EKHO", nameAr: "المصرية الكويتية القابضة", nameEn: "Egyptian Kuwait Holding" },
  { ticker: "MPRC", nameAr: "المدينة الإعلامية", nameEn: "Egyptian Media Production City" },
  { ticker: "MOED", nameAr: "المصرية للتعليم الحديث", nameEn: "Egyptian Modern Education Systems" },
  { ticker: "AREH", nameAr: "التجمع المصري العقاري", nameEn: "Real Estate Egyptian Consortium" },
  { ticker: "AREHA", nameAr: "التجمع المصري العقاري لحاملي الأسهم", nameEn: "Real Estate Egyptian Consortium Bearer Shares" },
  { ticker: "EGSA", nameAr: "المصرية للأقمار الصناعية (نيل سات)", nameEn: "Egyptian Satellites (NileSat)" },
  { ticker: "ESGI", nameAr: "المصرية للنشا والجلوكوز", nameEn: "Egyptian Starch & Glucose" },
  { ticker: "ETRS", nameAr: "المصرية للنقل والخدمات التجارية", nameEn: "Egyptian Transport & Commercial Services" },
  { ticker: "ABRD", nameAr: "المصريين بالخارج للاستثمار والتنمية", nameEn: "Egyptians Abroad For Investment & Development" },
  { ticker: "EIUD", nameAr: "المصريين للاستثمار والتنمية العمرانية", nameEn: "Egyptians For Investment & Urban Development" },
  { ticker: "EHDR", nameAr: "المصريين للإسكان والتعمير", nameEn: "Egyptians for Housing Development" },
  { ticker: "AFDI", nameAr: "الأهلي للتنمية والاستثمار", nameEn: "Al Ahly for Development & Investment" },
  { ticker: "EPPK", nameAr: "الأهرام للطباعة والتغليف", nameEn: "El Ahram Co. For Printing And Packing" },
  { ticker: "EEII", nameAr: "الصناعات الهندسية العربية", nameEn: "Arab Engineering Industries" },
  { ticker: "EALR", nameAr: "العربية لاستصلاح الأراضي", nameEn: "El Arabia For Land Reclamation" },
  { ticker: "EBDP", nameAr: "البدر للبلاستيك", nameEn: "El Badr Plastic" },
  { ticker: "ICFC", nameAr: "الدولية للأسمدة والكيماويات", nameEn: "El Dawlia Fertilizers And Chemicals" },
  { ticker: "IRAX", nameAr: "العز الدخيلة للصلب - الإسكندرية", nameEn: "El Ezz Aldekhela Steel - Alexandria" },
  { ticker: "ECAP", nameAr: "العز للسيراميك والبورسلين (جيما)", nameEn: "El Ezz Ceramics & Porcelain (Gemma)" },
  { ticker: "KWIN", nameAr: "القاهرة الوطنية للاستثمار", nameEn: "El Kahera El Watania Investment" },
  { ticker: "ELKA", nameAr: "القاهرة للإسكان", nameEn: "El Kahera Housing" },
  { ticker: "KABO", nameAr: "النصر للملابس والمنسوجات - كابو", nameEn: "El Nasr Clothes & Textiles - KABO" },
  { ticker: "ELNA", nameAr: "النصر لصناعة المحاصيل الزراعية", nameEn: "El Nasr For Manufacturing Agricultural Crops" },
  { ticker: "NASR", nameAr: "النصر للمحولات (الماكو)", nameEn: "El Nasr Transformers (El Maco)" },
  { ticker: "OBRI", nameAr: "العبور للاستثمار العقاري", nameEn: "El Ebour Real Estate Investment" },
  { ticker: "EOSB", nameAr: "العروبة للسمسرة", nameEn: "Al Orouba Securities Brokerage" },
  { ticker: "ELSH", nameAr: "الشمس للإسكان والتعمير", nameEn: "El Shams Housing & Urbanization" },
  { ticker: "SPHT", nameAr: "الشمس للأهرامات للفنادق والمشروعات السياحية", nameEn: "El Shams Pyramids For Hotels & Touristic Projects" },
  { ticker: "ELWA", nameAr: "الوادي للتنمية السياحية", nameEn: "El Wadi Touristic Development" },
  { ticker: "NIPH", nameAr: "النيل للأدوية والصناعات الكيماوية", nameEn: "El-Nile Co. For Pharmaceuticals And Chemical Industries" },
  { ticker: "ELEC", nameAr: "الكابلات الكهربائية المصرية", nameEn: "Electro Cable Egypt Company" },
  { ticker: "UEGC", nameAr: "السعيد للمقاولات والاستثمار العقاري", nameEn: "El Saeed Contracting and Real Estate Investment" },
  { ticker: "SWDY", nameAr: "السويدى للكهرباء", nameEn: "El Sewedy Electric Company" },
  { ticker: "EMFD", nameAr: "إعمار مصر للتنمية", nameEn: "Emaar Misr For Development" },
  { ticker: "ENGC", nameAr: "الصناعات الهندسية (أيكون)", nameEn: "Engineering Industries (Icon)" },
  { ticker: "EXPA", nameAr: "بنك تنمية الصادرات", nameEn: "Export Development Bank Of Egypt" },
  { ticker: "ZEOT", nameAr: "الزيوت والمستخلصات", nameEn: "Extracted Oils & Derivatives" },
  { ticker: "ESRS", nameAr: "العز للصلب", nameEn: "Ezz Steel" },
  { ticker: "FAIT", nameAr: "بنك فيصل الإسلامي المصري (جنيه)", nameEn: "Faisal Islamic Bank Of Egypt (EGP)" },
  { ticker: "FAITA", nameAr: "بنك فيصل الإسلامي المصري (دولار)", nameEn: "Faisal Islamic Bank Of Egypt (USD)" },
  { ticker: "FERC", nameAr: "فيركيم مصر للأسمدة والكيماويات", nameEn: "Ferchem Misr Company for Fertilizers and Chemicals" },
  { ticker: "FIRED", nameAr: "الأولى للاستثمار والتنمية العقارية", nameEn: "First Investment And Real Estate Development" },
  { ticker: "AUTO", nameAr: "جي بي أوتو", nameEn: "GB Auto" },
  { ticker: "AALR", nameAr: "العامة لاستصلاح الأراضي والتنمية", nameEn: "General Co for Land Reclamation Development and Reconstruction" },
  { ticker: "GSSC", nameAr: "العامة للصوامع والتخزين", nameEn: "General Company for Silos and Storage" },
  { ticker: "GETO", nameAr: "جينيل تورز", nameEn: "Genial Tours" },
  { ticker: "GIHD", nameAr: "غربيه الإسلامية للإسكان", nameEn: "Gharbia Islamic Housing Development" },
  { ticker: "GGCC", nameAr: "الجيزة العامة للمقاولات", nameEn: "Giza General Contracting" },
  { ticker: "BIOC", nameAr: "جلاكسو سميث كلاين", nameEn: "Glaxo Smith Kline" },
  { ticker: "GTHE", nameAr: "جلوبال للاتصالات القابضة", nameEn: "Global Telecom Holding" },
  { ticker: "GMCI", nameAr: "جي ام سي للاستثمارات الصناعية والتجارية", nameEn: "GMC Group For Industrial, Commercial And Financial Investments" },
  { ticker: "GOCO", nameAr: "الساحل الذهبي", nameEn: "Golden Coast Company" },
  { ticker: "GPPL", nameAr: "الميادين الذهبية", nameEn: "Golden Pyramids Plaza" },
  { ticker: "GTWL", nameAr: "الذهبية للمنسوجات والملابس الصوفية", nameEn: "Golden Textiles & Clothes Wool" },
  { ticker: "GRCA", nameAr: "جراند كابيتال للاستثمار", nameEn: "Grand Investment Capital" },
  { ticker: "AGIN", nameAr: "الاستثمار الخليجي العربي", nameEn: "Gulf Arab Investment" },
  { ticker: "CCRS", nameAr: "الخليج الكندي للاستثمار العقاري", nameEn: "Gulf Canadian Real Estate Investment Co." },
  { ticker: "HELI", nameAr: "هليوبوليس للإسكان والتعمير", nameEn: "Heliopolis Housing" },
  { ticker: "HDBK", nameAr: "بنك الإسكان والتعمير", nameEn: "Housing & Development Bank" },
  { ticker: "INEE", nameAr: "إندس والهندسة", nameEn: "Indus & Engineer" },
  { ticker: "INEG", nameAr: "المتكاملة للهندسة", nameEn: "Integrated Engineering Group Sae" },
  { ticker: "ICAL", nameAr: "إنتر-القاهرة للألومنيوم", nameEn: "Inter-Cairo For Aluminum Industry" },
  { ticker: "IFAP", nameAr: "المنتجات الزراعية الدولية", nameEn: "International Agricultural Products" },
  { ticker: "IBCT", nameAr: "المؤسسة الدولية للتجارة والامتياز", nameEn: "International Business Corporation For Trade And Franchise" },
  { ticker: "ICID", nameAr: "الدولية للاستثمار والتنمية", nameEn: "International Co For Investment & Development" },
  { ticker: "ICLE", nameAr: "الدولية للتأجير التمويلي (إنكوليز)", nameEn: "International Company For Leasing (Incolease)" },
  { ticker: "ICMI", nameAr: "الدولية للصناعات الطبية", nameEn: "International Company For Medical Industries" },
  { ticker: "DIFC", nameAr: "ثاني أكسيد الكربون الجاف الدولي", nameEn: "International Dry Ice" },
  { ticker: "IPPM", nameAr: "الدولية لمواد الطباعة والتغليف", nameEn: "International Printing & Packaging Materials Co." },
  { ticker: "IDRE", nameAr: "الإسماعيلية للتنمية والعقارات", nameEn: "Ismailia Development And Real Estate" },
  { ticker: "ISMA", nameAr: "الإسماعيلية مصر للدواجن", nameEn: "Ismailia Misr Poultry" },
  { ticker: "INFI", nameAr: "الإسماعيلية الوطنية للصناعات الغذائية", nameEn: "Ismailia National Food Industries" },
  { ticker: "ITSY", nameAr: "آي تي سينرجي", nameEn: "IT Synergy" },
  { ticker: "JUFO", nameAr: "جهينة للصناعات الغذائية", nameEn: "Juhayna Food Industries" },
  { ticker: "KZPC", nameAr: "كفر الزيات للمبيدات والكيماويات", nameEn: "Kafr El Zayat Pesticides and Chemicals" },
  { ticker: "LKGP", nameAr: "مجموعة لاقا", nameEn: "Lakah Group" },
  { ticker: "LCSW", nameAr: "ليسيكو مصر", nameEn: "Lecico Egypt" },
  { ticker: "MPCO", nameAr: "المنصورة للدواجن", nameEn: "Mansoura Poultry" },
  { ticker: "MOIL", nameAr: "موريديف وخدمات النفط", nameEn: "Maridive & Oil Services" },
  { ticker: "MMAT", nameAr: "مرسى مرسى علم للتنمية السياحية", nameEn: "Marsa Marsa Alam For Tourism Development" },
  { ticker: "MAAL", nameAr: "مرسيليا المصريه الخليجية القابضة", nameEn: "Marseille Almasreia Alkhalegeya For Holding Investment" },
  { ticker: "MBEN", nameAr: "إم بي للهندسة", nameEn: "MB Engineering" },
  { ticker: "MEPA", nameAr: "التعبئة الطبية", nameEn: "Medical Packaging Company" },
  { ticker: "MNHD", nameAr: "مدينة نصر للإسكان", nameEn: "Medinet Nasr Housing" },
  { ticker: "MPCI", nameAr: "ممفيس للأدوية", nameEn: "Memphis Pharmaceuticals" },
  { ticker: "MENA", nameAr: "مينا للاستثمار السياحي والعقاري", nameEn: "Mena Touristic & Real Estate Investment" },
  { ticker: "WCDF", nameAr: "مطاحن مصر الوسطى", nameEn: "Middle & West Delta Flour Mills" },
  { ticker: "MEGM", nameAr: "الشرق الأوسط لصناعة الزجاج", nameEn: "Middle East Glass Manufacturing" },
  { ticker: "CEFM", nameAr: "مطاحن مصر الوسطى", nameEn: "Middle Egypt Flour Mills" },
  { ticker: "MIPH", nameAr: "مينافارم للأدوية", nameEn: "Minapharm Pharmaceuticals" },
  { ticker: "MBSC", nameAr: "مصر بني سويف للإسمنت", nameEn: "Misr Beni Suef Cement" },
  { ticker: "MCQE", nameAr: "مصر للإسمنت قنا", nameEn: "Misr Cement (Qena)" },
  { ticker: "MICH", nameAr: "مصر للصناعات الكيماوية", nameEn: "Misr Chemical Industries" },
  { ticker: "MRCO", nameAr: "مصر للتبريد وتكييف الهواء", nameEn: "Misr Refrigeration and Air Conditioning" },
  { ticker: "MFSC", nameAr: "مصر فري شوب", nameEn: "Egypt Free Shops" },
  { ticker: "MEDA", nameAr: "مصر السلام للتنمية والتكنولوجيا", nameEn: "Misr Elsalam For Development & Advanced Technology" },
  { ticker: "MFINEG", nameAr: "مصر للاستثمارات المالية", nameEn: "Misr Financial Investments" },
  { ticker: "MFPC", nameAr: "مصر لإنتاج الأسمدة", nameEn: "Misr Fertilizers Production Company" },
  { ticker: "MHOT", nameAr: "مصر للفنادق", nameEn: "Misr Hotels" },
  { ticker: "MKIT", nameAr: "مصر الكويت للاستثمار والتجارة (ميتيلو)", nameEn: "Misr Kuwait Investment And Trading (Meatello)" },
  { ticker: "ATQA", nameAr: "مصر الوطنية للصلب - العتاقة", nameEn: "Misr National Steel - Ataqa" },
  { ticker: "MOSC", nameAr: "مصر للزيوت والصابون", nameEn: "Misr Oils & Soap" },
  { ticker: "WATP", nameAr: "الحديثة للموانع المائية", nameEn: "Modern Waterproofing Company" },
  { ticker: "SMPP", nameAr: "الشروق للطباعة الحديثة والتغليف", nameEn: "Shorouk for Modern Printing and Packaging" },
  { ticker: "MOIN", nameAr: "المهندس للتأمين", nameEn: "Mohandes Insurance" },
  { ticker: "NAHO", nameAr: "نعيم القابضة", nameEn: "NAEEM Holding" },
  { ticker: "NCCW", nameAr: "النصر لأعمال المدنية", nameEn: "Nasr Company For Civil Works" },
  { ticker: "NBKE", nameAr: "البنك الوطني الكويتي مصر", nameEn: "National Bank Of Kuwait Egypt" },
  { ticker: "NCEM", nameAr: "الإسمنت الوطنية", nameEn: "National Cement" },
  { ticker: "NCMP", nameAr: "الوطنية لمنتجات الذرة", nameEn: "National Company For Maize Products" },
  { ticker: "NDRL", nameAr: "الوطنية للحفر", nameEn: "National Drilling Company" },
  { ticker: "NHPS", nameAr: "الإسكان الوطني للنقابات المهنية", nameEn: "National Housing for Professional Syndicates" },
  { ticker: "COPR", nameAr: "النحاس للاستثمار والتطوير العقاري", nameEn: "Copper For Commercial Investment & Real Estate Development" },
  { ticker: "EGAS", nameAr: "الشركة المصرية للغاز", nameEn: "Egypt Gas Company" },
  { ticker: "NCIS", nameAr: "نيوكاسل للاستثمار الرياضي", nameEn: "New Castle For Investment Sports" },
  { ticker: "NCIN", nameAr: "استثمارات مدينة نيل سيتي", nameEn: "Nile City Investment" },
  { ticker: "NCGC", nameAr: "النيل لحليج الأقطان", nameEn: "Nile Cotton Ginning" },
  { ticker: "NOAF", nameAr: "شمال أفريقيا للاستثمار العقاري", nameEn: "North Africa Company For Real Estate Investment" },
  { ticker: "MILS", nameAr: "مطاحن شمال القاهرة", nameEn: "North Cairo Flour Mills" },
  { ticker: "NEDA", nameAr: "شمال الصعيد للتنمية والإنتاج الزراعي", nameEn: "North Upper Egypt Development & Agricultural Production" },
  { ticker: "NINH", nameAr: "مستشفى النزهة الدولي", nameEn: "Nozha International Hospital" },
  { ticker: "OCPH", nameAr: "أكتوبر فارما", nameEn: "October Pharma" },
  { ticker: "OCIC", nameAr: "أوراسكوم للإنشاء والصناعة", nameEn: "Orascom Construction Industries" },
  { ticker: "ODHN", nameAr: "أوراسكوم للتنمية القابضة", nameEn: "Orascom Development Holding AG" },
  { ticker: "ORHD", nameAr: "أوراسكوم للفنادق والتنمية", nameEn: "Orascom Hotels And Development" },
  { ticker: "OTMT", nameAr: "أوراسكوم للاستثمار القابضة", nameEn: "Orascom Investment Holding" },
  { ticker: "ORWE", nameAr: "النساجون الشرقيون للسجاد", nameEn: "Oriental Weavers Carpet" },
  { ticker: "EBSC", nameAr: "أسوول إي إس بي للسمسرة", nameEn: "Osool ESB Securities Brokerage" },
  { ticker: "PACH", nameAr: "الدهانات والصناعات الكيماوية", nameEn: "Paint & Chemicals Industries" },
  { ticker: "PHDC", nameAr: "بالم هيلز للتطوير", nameEn: "Palm Hills Development Company" },
  { ticker: "SIMO", nameAr: "ورق الشرق الأوسط (سيمو)", nameEn: "Paper Middle East (Simo)" },
  { ticker: "PTCC", nameAr: "فرعون تك للتحكم والاتصالات", nameEn: "Pharaoh Tech For Control And Communication Systems" },
  { ticker: "ASPI", nameAr: "أسبر كابيتال للاستثمارات المالية", nameEn: "Aspire Capital Holding For Financial Investments" },
  { ticker: "PSAD", nameAr: "بورسعيد للتنمية الزراعية والإنشاء", nameEn: "Port Said Agricultural Development and Construction" },
  { ticker: "ARAB", nameAr: "المطورون العرب القابضة", nameEn: "Arab Developers Holding" },
  { ticker: "PRMH", nameAr: "بريمير القابضة", nameEn: "Prime Holding" },
  { ticker: "PHTV", nameAr: "فنادق ومنتجعات الأهرامات", nameEn: "Pyramisa Hotels and Resorts" },
  { ticker: "QNBA", nameAr: "قطر الوطني الأهلي", nameEn: "Qatar National Bank Alahly" },
  { ticker: "RAKT", nameAr: "العامة لصناعة الورق راكتا", nameEn: "General Company for Paper Industry Rakta" },
  { ticker: "RACC", nameAr: "راية لمراكز الاتصال", nameEn: "Raya Contact Center" },
  { ticker: "RAYA", nameAr: "راية القابضة للاستثمارات المالية", nameEn: "Raya Holding for Financial Investments" },
  { ticker: "REAC", nameAr: "ريكاب للاستثمارات المالية", nameEn: "Reacap Financial Investments" },
  { ticker: "RTVC", nameAr: "ريمكو لإنشاء القرى السياحية", nameEn: "Remco For Touristic Villages Construction" },
  { ticker: "RIVA", nameAr: "ريفا فارما", nameEn: "Riva Pharma" },
  { ticker: "RMTV", nameAr: "رواد مصر للاستثمار السياحي", nameEn: "Rowad Misr Tourism Investment" },
  { ticker: "ROTO", nameAr: "رواد السياحة (الرواد)", nameEn: "Rowad Tourism (Al Rowad)" },
  { ticker: "RUBX", nameAr: "روبكس الدولية للبلاستيك والأكريليك", nameEn: "Rubex International For Plastic And Acrylic Manufacturing" },
  { ticker: "SIPC", nameAr: "صابا الدولية للأدوية والكيماويات", nameEn: "Sabaa International Company For Pharmaceutical And Chemical" },
  { ticker: "SMFR", nameAr: "صمد مصر إيجيفرت", nameEn: "Samad Misr EGYFERT" },
  { ticker: "SMCS", nameAr: "سامكريت مصر", nameEn: "Samcrete Misr" },
  { ticker: "SMCSA", nameAr: "سامكريت مصر أسهم ممتازة", nameEn: "Samcrete Misr Preferred Shares" },
  { ticker: "SEIG", nameAr: "الاستثمار والتمويل السعودي المصري", nameEn: "Saudi Egyptian Investment & Finance" },
  { ticker: "SEIGA", nameAr: "الاستثمار والتمويل السعودي المصري (دولار)", nameEn: "Saudi Egyptian Investment & Finance (Usd)" },
  { ticker: "SNFC", nameAr: "الشرقية الوطنية للأمن الغذائي", nameEn: "Sharkia National Company for Food Security" },
  { ticker: "SDTI", nameAr: "شركة شرم دريمز للاستثمار السياحي", nameEn: "Sharm Dreams Co For Tourism Investment" },
  { ticker: "SKPC", nameAr: "بتروكيماويات سيدي كرير", nameEn: "Sidi Kerir Petrochemicals" },
  { ticker: "SCEM", nameAr: "سيناء للإسمنت", nameEn: "Sinai Cement" },
  { ticker: "OCDI", nameAr: "السادس من أكتوبر للتنمية والاستثمار (سوديك)", nameEn: "Six Of October Development & Investment (Sodic)" },
  { ticker: "SLTD", nameAr: "سكاى لايت للتنمية السياحية", nameEn: "Sky Light For Tourist Development Company" },
  { ticker: "SAIB", nameAr: "المصرف العربي الدولي", nameEn: "Societe Arabe Internationale De Banque" },
  { ticker: "SNFI", nameAr: "سوهاج الوطنية للصناعات الغذائية", nameEn: "Sohag National Company For Food Industries" },
  { ticker: "SCFM", nameAr: "مطاحن ومخابز جنوب القاهرة والجيزة", nameEn: "South Cairo & Giza Mills & Bakeries" },
  { ticker: "SVCE", nameAr: "أسمنت جنوب الوادي", nameEn: "South Valley Cement" },
  { ticker: "SCTS", nameAr: "قناة السويس للتكنولوجيا والتسوية", nameEn: "Sues Canal Company For Technology Settling" },
  { ticker: "SBAG", nameAr: "أكياس السويس", nameEn: "Suez Bags" },
  { ticker: "CANA", nameAr: "بنك قناة السويس", nameEn: "Suez Canal Bank" },
  { ticker: "SUCE", nameAr: "أسمنت السويس", nameEn: "Suez Cement" },
  { ticker: "TMGH", nameAr: "طلعت مصطفى القابضة", nameEn: "TMG Holding" },
  { ticker: "TECH", nameAr: "تغليف الصناعات - مصر", nameEn: "Taghleef Industries - Egypt" },
  { ticker: "ETEL", nameAr: "المصرية للاتصالات", nameEn: "Telecom Egypt" },
  { ticker: "ADPC", nameAr: "الألبان العربية", nameEn: "The Arab Dairy Products" },
  { ticker: "TORA", nameAr: "أسمنت طرة", nameEn: "Tourah Cement" },
  { ticker: "TOUR", nameAr: "السياحة والتعمير", nameEn: "Tourism Urbanization" },
  { ticker: "TRTO", nameAr: "ترانس أوشن تورز", nameEn: "Trans Oceans Tours" },
  { ticker: "UNBE", nameAr: "البنك الاتحادي الوطني مصر", nameEn: "Union National Bank Egypt" },
  { ticker: "UASG", nameAr: "الشحن العربي المتحدة", nameEn: "United Arab Stevedoring" },
  { ticker: "UNIT", nameAr: "المتحدة للإسكان والتعمير", nameEn: "United Housing & Development" },
  { ticker: "UNIP", nameAr: "العالمية لمواد التعبئة والورق", nameEn: "Universal Company for Packaging Materials and Paper" },
  { ticker: "UNFO", nameAr: "يونيفرت للصناعات الغذائية", nameEn: "Univert Food Industries" },
  { ticker: "UEFM", nameAr: "مطاحن مصر العليا", nameEn: "Upper Egypt Flour Mills" },
  { ticker: "UTOP", nameAr: "يوتوبيا للاستثمار العقاري والسياحي", nameEn: "Utopia Real Estate Investment and Tourism" },
  { ticker: "VERT", nameAr: "فيرتيكا", nameEn: "Vertika" },
  { ticker: "VODE", nameAr: "فودافون مصر", nameEn: "Vodafone Egypt" },
  { ticker: "WKOL", nameAr: "وادي كوم أمبو لاستصلاح الأراضي", nameEn: "Wadi Kom Ombo for Land Reclamation" },
  { ticker: "XPIN", nameAr: "اكسبريس للتكامل", nameEn: "Xpress Integration" },
  { ticker: "ZMID", nameAr: "زهراء المعادي للاستثمار والتنمية", nameEn: "Zahraa Maadi Investment & Development" },
  { ticker: "DOMT", nameAr: "العربية للصناعات الغذائية (دومتي)", nameEn: "Arabian Food Industries(DOMTY)" },
  { ticker: "CLHO", nameAr: "مستشفى كليوباترا", nameEn: "Cleopatra Hospital" },
  { ticker: "OLFI", nameAr: "أرض العبور للصناعات الغذائية", nameEn: "Obour Land For Food Industries" },
  { ticker: "MTIE", nameAr: "إم إم جروب للصناعة والتجارة الدولية", nameEn: "MM Group For Industry And International Trade" },
  { ticker: "CICH", nameAr: "سي كابيتال القابضة للاستثمارات المالية", nameEn: "CI Capital Holding for Financial Investments" },
  { ticker: "CIRA", nameAr: "القاهرة للاستثمار والتنمية العقارية", nameEn: "Cairo For Investment And Real Estate Development" },
  { ticker: "CNFN", nameAr: "كونتكت المالية القابضة", nameEn: "Contact Financial Holding" },
  { ticker: "SRWA", nameAr: "صروة كابيتال", nameEn: "Sarwa Capital" },
  { ticker: "FWRY", nameAr: "فوري لتكنولوجيا البنوك والمدفوعات الإلكترونية", nameEn: "Fawry for Banking Technology and Electronic Payment" },
  { ticker: "ODIN", nameAr: "أودين للاستثمار", nameEn: "ODIN Investment" },
  { ticker: "RMDA", nameAr: "العاشر من رمضان للأدوية والمستحضرات التشخيصية - راميدا", nameEn: "Tenth of Ramadan for Pharmaceutical Industries and Diagnostic Reagents - Rameda" },
  { ticker: "AIVCB", nameAr: "الأعراف للاستثمار والاستشارات بالجنيه", nameEn: "Al Arafa Investment And Consulting in EGP" },
  { ticker: "SPMD", nameAr: "سبيد ميديكال", nameEn: "Speed Medical" },
  { ticker: "OFH", nameAr: "أوراسكوم المالية القابضة", nameEn: "Orascom Financial Holdings" },
  { ticker: "ACAMD", nameAr: "العربية لإدارة الأصول والتنمية", nameEn: "Arab Company for Asset Management And Development" },
  { ticker: "ISPH", nameAr: "ابن سينا فارما", nameEn: "Ibnsina Pharma" },
  { ticker: "TALM", nameAr: "تعليم لإدارة الخدمات", nameEn: "Taaleem Management Services" },
  { ticker: "IDHC", nameAr: "المتكاملة للتشخيص القابضة", nameEn: "Integrated Diagnostics Holdings" },
  { ticker: "ISMQ", nameAr: "الحديد والصلب للمناجم والمحاجر", nameEn: "Iron and Steel for Mines and Quarries" },
  { ticker: "TANM", nameAr: "تنمية للاستثمار العقاري", nameEn: "Tanmiya for Real Estate Investment" },
  { ticker: "EFIH", nameAr: "إي-فاينانس للاستثمارات الرقمية والمالية", nameEn: "E-finance For Digital and Financial Investments" },
  { ticker: "GDWA", nameAr: "جدوى للتنمية الصناعية", nameEn: "Gadwa For Industrial Development" },
  { ticker: "PRDC", nameAr: "رواد الخصائص للتنمية العمرانية", nameEn: "Pioneers Properties For Urban Development" },
  { ticker: "KRDI", nameAr: "نهر الخير للتنمية والاستثمار الزراعي", nameEn: "Al Khair River For Development Agricultural Investment" },
  { ticker: "MCRO", nameAr: "ماكرو جروب للأدوية", nameEn: "Macro Group Pharmaceuticals" },
  { ticker: "ODID", nameAr: "أودين للاستثمار والتنمية", nameEn: "Odin for Investment & Development" },
];

export function getStockName(ticker: string, lang: 'ar' | 'en' = 'ar'): string {
  const stock = EGX_STOCKS.find((s) => s.ticker.toUpperCase() === ticker.toUpperCase());
  if (!stock) return ticker;
  return lang === 'ar' ? stock.nameAr : stock.nameEn;
}

export function getStockInfo(ticker: string): EGXStock | undefined {
  return EGX_STOCKS.find((s) => s.ticker.toUpperCase() === ticker.toUpperCase());
}

