import { prisma } from '../lib/prisma.ts';
import { GicsSector } from '@prisma/client';
import { EGX_STOCKS } from '../../src/lib/egxStocks.ts';

const SECTOR_MAP: Record<string, GicsSector> = {
  'راية القابضة': GicsSector.INFORMATION_TECHNOLOGY,
  'المجموعة المتكاملة': GicsSector.INFORMATION_TECHNOLOGY,
  'قناة السويس لتوطين التكنولوجيا': GicsSector.INFORMATION_TECHNOLOGY,
  'نوفيدا للاستثمار والتكنولوجيا': GicsSector.INFORMATION_TECHNOLOGY,
  'فوري': GicsSector.INFORMATION_TECHNOLOGY,
  'اي فاينانس': GicsSector.INFORMATION_TECHNOLOGY,
  'ڤاليو': GicsSector.INFORMATION_TECHNOLOGY,
  'ديجيتايز للاستثمار والتقنية': GicsSector.INFORMATION_TECHNOLOGY,
  'ايكون': GicsSector.INFORMATION_TECHNOLOGY,
  'دايس': GicsSector.INFORMATION_TECHNOLOGY,
  'انترناشيونال بزنيس': GicsSector.INFORMATION_TECHNOLOGY,
  'الاسكندرية للأدوية': GicsSector.HEALTH_CARE,
  'جلاكسو سميثكلاين': GicsSector.HEALTH_CARE,
  'القاهرة للأدوية': GicsSector.HEALTH_CARE,
  'مستشفي كليوباترا': GicsSector.HEALTH_CARE,
  'الاسكندرية للخدمات الطبية': GicsSector.HEALTH_CARE,
  'العبوات الدوائية': GicsSector.HEALTH_CARE,
  'العبوات الطبية': GicsSector.HEALTH_CARE,
  'مينا فارم للأودية': GicsSector.HEALTH_CARE,
  'ممفيس للأدوية': GicsSector.HEALTH_CARE,
  'أكتوبر فارما': GicsSector.HEALTH_CARE,
  'نيوداب': GicsSector.HEALTH_CARE,
  'سبيد ميديكال': GicsSector.HEALTH_CARE,
  'راميدا': GicsSector.HEALTH_CARE,
  'فاروتك': GicsSector.HEALTH_CARE,
  'الاتحاد الصيدلي': GicsSector.HEALTH_CARE,
  'ابن سينا': GicsSector.HEALTH_CARE,
  'ماكرو جروب': GicsSector.HEALTH_CARE,
  'بريميم هيلثكير جروب': GicsSector.HEALTH_CARE,
  'فتنس برايم للاندية الصحية': GicsSector.HEALTH_CARE,
  'البنك التجاري الدولي (مصر)': GicsSector.FINANCIALS,
  'البنك التجاري الدولي': GicsSector.FINANCIALS,
  'هيرمس': GicsSector.FINANCIALS,
  'القلعة للاستشارات المالية': GicsSector.FINANCIALS,
  'فالمور القابضة للاستثمار': GicsSector.FINANCIALS,
  'اسباير كابيتال': GicsSector.FINANCIALS,
  'بنك التعمير': GicsSector.FINANCIALS,
  'المالية والصناعية': GicsSector.FINANCIALS,
  'الغربية الإسلامية': GicsSector.FINANCIALS,
  'جراند انفستمنت': GicsSector.FINANCIALS,
  'العالمية للاستثمار والتنمية': GicsSector.FINANCIALS,
  'ليسيكو مصر': GicsSector.FINANCIALS,
  'مينا للاستثمار': GicsSector.FINANCIALS,
  'النعيم القابضة': GicsSector.FINANCIALS,
  'العربية المتحدة': GicsSector.FINANCIALS,
  'العرفة للاستثمارات': GicsSector.FINANCIALS,
  'المهندس للتأمين': GicsSector.FINANCIALS,
  'بنك قناة السويس': GicsSector.FINANCIALS,
  'كريدي أجريكول': GicsSector.FINANCIALS,
  'بنك قطر الوطني': GicsSector.FINANCIALS,
  'دلتا للتأمين': GicsSector.FINANCIALS,
  'البنك المصري الخليجي': GicsSector.FINANCIALS,
  'برايم القابضة': GicsSector.FINANCIALS,
  'بنك الشركة المصرفية': GicsSector.FINANCIALS,
  'فيصل الإسلامي - جنيه': GicsSector.FINANCIALS,
  'بنك فيصل - بالدولار': GicsSector.FINANCIALS,
  'ارابيا انفستمنتس': GicsSector.FINANCIALS,
  'أطلس': GicsSector.FINANCIALS,
  'الملتقى للاستثمارات': GicsSector.FINANCIALS,
  'بلتون المالية القابضة': GicsSector.FINANCIALS,
  'القاهرة للاستثمار': GicsSector.FINANCIALS,
  'إى إس بى للوساطة': GicsSector.FINANCIALS,
  'الوادي للاستثمار والتنمية': GicsSector.FINANCIALS,
  'العروبة للسمسرة': GicsSector.FINANCIALS,
  'أودن': GicsSector.FINANCIALS,
  'الأهلي للتنمية': GicsSector.FINANCIALS,
  'رواد': GicsSector.FINANCIALS,
  'بنك البركة': GicsSector.FINANCIALS,
  'ركاز القابضة للاستثمارات المالية': GicsSector.FINANCIALS,
  'المصرية الكويتية': GicsSector.FINANCIALS,
  'الأولى للاستثمار': GicsSector.FINANCIALS,
  'أوراسكوم المالية القابضة': GicsSector.FINANCIALS,
  'أوراسكوم للاستثمار': GicsSector.FINANCIALS,
  'التوفيق للتأجير التمويلي': GicsSector.FINANCIALS,
  'بي إنفستمنتس القابضة': GicsSector.FINANCIALS,
  'سي آي كابيتال': GicsSector.FINANCIALS,
  'العربية للإدارة والتطوير': GicsSector.FINANCIALS,
  'كونتكت المالية': GicsSector.FINANCIALS,
  'أكت فاينانشال': GicsSector.FINANCIALS,
  'المصرف المتحد': GicsSector.FINANCIALS,
  'كاتليست بارتنرز': GicsSector.FINANCIALS,
  'ارابيا انفستمنتس هولدنج': GicsSector.FINANCIALS,
  'توسع للتخصيم': GicsSector.FINANCIALS,
  'ايه كابيتال القابضة': GicsSector.FINANCIALS,
  'آراب للتنمية': GicsSector.FINANCIALS,
  'إم بي': GicsSector.FINANCIALS,
  'نهر الخير للتنمية': GicsSector.FINANCIALS,
  'فالمور': GicsSector.FINANCIALS,
  'الخليج للاستثمارات العربية': GicsSector.FINANCIALS,
  'الوطني': GicsSector.FINANCIALS,
  'أبو ظبي الإسلامي': GicsSector.FINANCIALS,
  'المصرية للمنتجعات': GicsSector.CONSUMER_DISCRETIONARY,
  'جي بي أوتو': GicsSector.CONSUMER_DISCRETIONARY,
  'القناة للتوكيلات': GicsSector.CONSUMER_DISCRETIONARY,
  'الجوهرة': GicsSector.CONSUMER_DISCRETIONARY,
  'النزهة الدولية': GicsSector.CONSUMER_DISCRETIONARY,
  'النساجون الشرقيون': GicsSector.CONSUMER_DISCRETIONARY,
  'سبينالكس': GicsSector.CONSUMER_DISCRETIONARY,
  'مصر للفنادق': GicsSector.CONSUMER_DISCRETIONARY,
  'بيراميزا': GicsSector.CONSUMER_DISCRETIONARY,
  'جولدن كوست': GicsSector.CONSUMER_DISCRETIONARY,
  'جولدن تكس للاصواف': GicsSector.CONSUMER_DISCRETIONARY,
  'القاهرة للخدمات التعليمية': GicsSector.CONSUMER_DISCRETIONARY,
  'شارم دريمز': GicsSector.CONSUMER_DISCRETIONARY,
  'الشمس بيراميدز للمنشات السياحية': GicsSector.CONSUMER_DISCRETIONARY,
  'مرسى مرسى علم للتنمية السياحية': GicsSector.CONSUMER_DISCRETIONARY,
  'جينيال تورز': GicsSector.CONSUMER_DISCRETIONARY,
  'عامر جروب': GicsSector.CONSUMER_DISCRETIONARY,
  'ام.ام جروب': GicsSector.CONSUMER_DISCRETIONARY,
  'بي آي جي': GicsSector.CONSUMER_DISCRETIONARY,
  'المصرية لنظم التعليم': GicsSector.CONSUMER_DISCRETIONARY,
  'تعليم لخدمات الإدارة': GicsSector.CONSUMER_DISCRETIONARY,
  'سيتي تريد': GicsSector.CONSUMER_DISCRETIONARY,
  'جي إم سي': GicsSector.CONSUMER_DISCRETIONARY,
  'المصرية للدواجن': GicsSector.CONSUMER_STAPLES,
  'مطاحن مصر الوسطى': GicsSector.CONSUMER_STAPLES,
  'القاهره للزيوت والصابون': GicsSector.CONSUMER_STAPLES,
  'النصر للحاصلات': GicsSector.CONSUMER_STAPLES,
  'الاسماعيلية للدواجن': GicsSector.CONSUMER_STAPLES,
  'كابو': GicsSector.CONSUMER_STAPLES,
  'مصر للزيوت والصابون': GicsSector.CONSUMER_STAPLES,
  'المنصورة للدواجن': GicsSector.CONSUMER_STAPLES,
  'القاهرة للدواجن': GicsSector.CONSUMER_STAPLES,
  'الدلتا للسكر': GicsSector.CONSUMER_STAPLES,
  'مخابز الإسكندرية': GicsSector.CONSUMER_STAPLES,
  'مصر للأسواق': GicsSector.CONSUMER_STAPLES,
  'مطاحن شمال القاهرة': GicsSector.CONSUMER_STAPLES,
  'مطاحن شرق الدلتا': GicsSector.CONSUMER_STAPLES,
  'مطاحن جنوب القاهرة والجيزة': GicsSector.CONSUMER_STAPLES,
  'العامة للصوامع': GicsSector.CONSUMER_STAPLES,
  'مطاحن مصر العليا': GicsSector.CONSUMER_STAPLES,
  'مطاحن وسط وغرب الدلتا': GicsSector.CONSUMER_STAPLES,
  'آراب ديرى - باندا': GicsSector.CONSUMER_STAPLES,
  'الدولية للمحاصيل': GicsSector.CONSUMER_STAPLES,
  'أكرو مصر': GicsSector.CONSUMER_STAPLES,
  'ايسترن كومباني': GicsSector.CONSUMER_STAPLES,
  'فوديكو': GicsSector.CONSUMER_STAPLES,
  'جهينة الغذائية': GicsSector.CONSUMER_STAPLES,
  'دومتي': GicsSector.CONSUMER_STAPLES,
  'إيديتا للصناعات الغذائية': GicsSector.CONSUMER_STAPLES,
  'سوهاج للصناعات الغذائية': GicsSector.CONSUMER_STAPLES,
  'عبور لاند الغذائية': GicsSector.CONSUMER_STAPLES,
  'يونيفرت الغذائية': GicsSector.CONSUMER_STAPLES,
  'يونيراب': GicsSector.CONSUMER_STAPLES,
  'ثمار': GicsSector.CONSUMER_STAPLES,
  'فرتيكا': GicsSector.CONSUMER_STAPLES,
  'لوتس للتنمية والاستثمار الزراعي': GicsSector.CONSUMER_STAPLES,
  'جو جرين': GicsSector.CONSUMER_STAPLES,
  'بونى': GicsSector.CONSUMER_STAPLES,
  'جورميه ايجيبت دوت كوم للاغذية': GicsSector.CONSUMER_STAPLES,
  'الزيوت المستخلصه ومنتجاتها': GicsSector.CONSUMER_STAPLES,
  'سيدي كرير': GicsSector.ENERGY,
  'أموك': GicsSector.ENERGY,
  'الخليجية الكندية': GicsSector.ENERGY,
  'أدكو': GicsSector.ENERGY,
  'غاز مصر': GicsSector.ENERGY,
  'الحفر الوطنية': GicsSector.ENERGY,
  'طاقة عربية': GicsSector.ENERGY,
  'الكابلات الكهربائية': GicsSector.INDUSTRIALS,
  'ماريديف': GicsSector.INDUSTRIALS,
  'السويدي': GicsSector.INDUSTRIALS,
  'الصعيد العامة SCCD': GicsSector.INDUSTRIALS,
  'المجموعة المصرية': GicsSector.INDUSTRIALS,
  'التعمير والاستشارات': GicsSector.INDUSTRIALS,
  'دلتا للإنشاء': GicsSector.INDUSTRIALS,
  'ايجيترانس': GicsSector.INDUSTRIALS,
  'الجيزة للمقاولات': GicsSector.INDUSTRIALS,
  'النصر للأعمال المدنية': GicsSector.INDUSTRIALS,
  'روبكس': GicsSector.INDUSTRIALS,
  'إيجيفرت': GicsSector.INDUSTRIALS,
  'الشرقية الوطنية': GicsSector.INDUSTRIALS,
  'عبر المحيطات': GicsSector.INDUSTRIALS,
  'العامة لاستصلاح الأراضي': GicsSector.INDUSTRIALS,
  'الإسكندرية للحاويات': GicsSector.INDUSTRIALS,
  'العربية للصناعات الهندسية': GicsSector.INDUSTRIALS,
  'المصرية للمشروعات': GicsSector.INDUSTRIALS,
  'السعودية المصرية': GicsSector.INDUSTRIALS,
  'المصري لتنمية الصادرات': GicsSector.INDUSTRIALS,
  'العربية للمحابس': GicsSector.INDUSTRIALS,
  'العربية لاستصلاح الاراضي': GicsSector.INDUSTRIALS,
  'المشروعات الصناعية والهندسية': GicsSector.INDUSTRIALS,
  'أوراسكوم للإنشاءات': GicsSector.INDUSTRIALS,
  'النيل': GicsSector.INDUSTRIALS,
  'الاسكندرية الوطنية': GicsSector.INDUSTRIALS,
  'إنكوليس': GicsSector.INDUSTRIALS,
  'إليكو': GicsSector.INDUSTRIALS,
  'وادي كوم امبو لاستصلاح الاراضي': GicsSector.INDUSTRIALS,
  'الفنار للمقاولات': GicsSector.INDUSTRIALS,
  'ايكمي': GicsSector.INDUSTRIALS,
  'لكح جروب': GicsSector.INDUSTRIALS,
  'جدوى للتنمية الصناعية': GicsSector.INDUSTRIALS,
  'جيتكس للاستثمارات التجارية والصناعية': GicsSector.INDUSTRIALS,
  'البدر': GicsSector.INDUSTRIALS,
  'العربية لحليج الأقطان': GicsSector.MATERIALS,
  'حديد عز': GicsSector.MATERIALS,
  'جنوب الوادى للأسمنت': GicsSector.MATERIALS,
  'أسكوم': GicsSector.MATERIALS,
  'دلتا للطباعة والتغليف': GicsSector.MATERIALS,
  'النيل لحليج الاقطان': GicsSector.MATERIALS,
  'راكتا': GicsSector.MATERIALS,
  'يونيباك': GicsSector.MATERIALS,
  'أبو قير للأسمدة': GicsSector.MATERIALS,
  'مصر بنى سويف للأسمنت': GicsSector.MATERIALS,
  'قنا': GicsSector.MATERIALS,
  'القومية للأسمنت': GicsSector.MATERIALS,
  'باكين': GicsSector.MATERIALS,
  'ايبيكو': GicsSector.MATERIALS,
  'كيما': GicsSector.MATERIALS,
  'أسمنت سيناء': GicsSector.MATERIALS,
  'العز الدخيلة للصلب': GicsSector.MATERIALS,
  'كفر الزيات للمبيدات': GicsSector.MATERIALS,
  'الاسكندرية للأسمنت': GicsSector.MATERIALS,
  'الألومنيوم العربية': GicsSector.MATERIALS,
  'مصر للالومنيوم': GicsSector.MATERIALS,
  'الاهرام للطباعة والتغليف': GicsSector.MATERIALS,
  'الشروق الحديثة للطباعة والتغليف': GicsSector.MATERIALS,
  'الشرق الأوسط للزجاج': GicsSector.MATERIALS,
  'مصر للكيماويات': GicsSector.MATERIALS,
  'الحديد والصلب': GicsSector.MATERIALS,
  'شيني': GicsSector.MATERIALS,
  'الصخور العربية': GicsSector.MATERIALS,
  'سبأ للصناعات الكيماوية': GicsSector.MATERIALS,
  'موبكو': GicsSector.MATERIALS,
  'فيركيم': GicsSector.MATERIALS,
  'الحديد والصلب للمناجم والمحاجر': GicsSector.MATERIALS,
  'مصر انتركونتننتل لصناعة الجرانيت والرخام': GicsSector.MATERIALS,
  'الوطنية للطباعة': GicsSector.MATERIALS,
  'عتاقة': GicsSector.MATERIALS,
  'الدولية للأسمدة': GicsSector.MATERIALS,
  'أسمنت طرة': GicsSector.MATERIALS,
  'كريست مارك للمقاولات والتطوير العقاري': GicsSector.REAL_ESTATE,
  'القاهرة للإسكان': GicsSector.REAL_ESTATE,
  'كوبر للاستثمار التجاري والتطوير العقاري': GicsSector.REAL_ESTATE,
  'سوديك': GicsSector.REAL_ESTATE,
  'بالم هيلز': GicsSector.REAL_ESTATE,
  'رمكو': GicsSector.REAL_ESTATE,
  'طلعت مصطفى': GicsSector.REAL_ESTATE,
  'مصر الجديدة للاسكان والتعمير': GicsSector.REAL_ESTATE,
  'مدينة نصر للاسكان': GicsSector.REAL_ESTATE,
  'المصريين للاسكان': GicsSector.REAL_ESTATE,
  'الشمس للإسكان': GicsSector.REAL_ESTATE,
  'المتحدة للاسكان': GicsSector.REAL_ESTATE,
  'زهراء المعادي': GicsSector.REAL_ESTATE,
  'جي بي آي للنمو العمراني': GicsSector.REAL_ESTATE,
  'جولدن بيراميدز بلازا': GicsSector.REAL_ESTATE,
  'الإسماعيلية الجديدة للتطوير والتنمية العمرانية': GicsSector.REAL_ESTATE,
  'الوطنية للاسكان': GicsSector.REAL_ESTATE,
  'شمال افريقيا للاستثمار العقاري': GicsSector.REAL_ESTATE,
  'العبور للاستثمار العقاري': GicsSector.REAL_ESTATE,
  'أوراسكوم للتنمية': GicsSector.REAL_ESTATE,
  'مجموعة النعيم العقارية القابضة': GicsSector.REAL_ESTATE,
  'إعمار مصر': GicsSector.REAL_ESTATE,
  'المطورون العرب': GicsSector.REAL_ESTATE,
  'ريماس': GicsSector.REAL_ESTATE,
  'مرسيليا المصرية الخليجية': GicsSector.REAL_ESTATE,
  'تنمية للاستثمار العقاري': GicsSector.REAL_ESTATE,
  'المصريين العقاري': GicsSector.REAL_ESTATE,
  'بايونيرز بروبرتيز': GicsSector.REAL_ESTATE,
  'هيبكو للاستثمارات التجارية والتنمية العقارية': GicsSector.REAL_ESTATE,
  'يوتوبيا': GicsSector.REAL_ESTATE,
  'ديفكو 2': GicsSector.REAL_ESTATE,
  'أجواء': GicsSector.REAL_ESTATE,
  'المصرية للاتصالات': GicsSector.COMMUNICATION_SERVICES,
  'مدينة الإنتاج الإعلامي': GicsSector.COMMUNICATION_SERVICES,
  'جلوبال تيلكوم': GicsSector.COMMUNICATION_SERVICES,
  'نايل سات': GicsSector.COMMUNICATION_SERVICES,
  'فودافون مصر': GicsSector.COMMUNICATION_SERVICES,
  'راية للاتصالات': GicsSector.COMMUNICATION_SERVICES,
};

async function seedSectors() {
  console.log('🚀 Starting sector seeding...\n');

  // 1) Ensure all 269 stocks exist (upsert from EGX_STOCKS)
  console.log('Syncing stocks from EGX list...');
  for (const s of EGX_STOCKS) {
    await prisma.stock.upsert({
      where: { ticker: s.ticker },
      create: { ticker: s.ticker, nameAr: s.nameAr, nameEn: s.nameEn },
      update: { nameAr: s.nameAr, nameEn: s.nameEn },
    });
  }
  console.log(`✅ Synced ${EGX_STOCKS.length} stocks.\n`);

  let updated = 0;
  let notFound = 0;
  const missing: string[] = [];

  for (const [nameAr, sector] of Object.entries(SECTOR_MAP)) {
    const result = await prisma.stock.updateMany({
      where: { nameAr: { contains: nameAr.trim() } },
      data: { sector },
    });

    if (result.count > 0) {
      updated += result.count;
      console.log(`✅ ${nameAr} → ${sector}`);
    } else {
      notFound++;
      missing.push(nameAr);
      console.log(`⚠️  Not found: ${nameAr}`);
    }
  }

  console.log(`\n━━━━━━━━━━━━━━━━━━━━━━━━━━━`);
  console.log(`✅ Updated: ${updated} stocks`);
  console.log(`⚠️  Not found: ${notFound} companies`);
  if (missing.length > 0) {
    console.log(`\nMissing companies:\n${missing.join('\n')}`);
  }

  await prisma.$disconnect();
}

seedSectors().catch(console.error);
