import type { Prisma } from '@prisma/client';

/**
 * User columns needed for API payloads (sanitizeUser / toUserPayload).
 * Excludes secrets and heavy unused columns (passwordHash, refreshTokens, etc.).
 */
export const userApiSelect = {
  id: true,
  email: true,
  phone: true,
  fullName: true,
  username: true,
  isEmailVerified: true,
  twoFactorEnabled: true,
  avatarUrl: true,
  riskTolerance: true,
  investmentHorizon: true,
  monthlyBudget: true,
  shariaMode: true,
  onboardingCompleted: true,
  interestedSectors: true,
  language: true,
  theme: true,
  plan: true,
  planExpiresAt: true,
  aiAnalysisUsedThisMonth: true,
  aiAnalysisResetDate: true,
  referralCode: true,
  referredBy: true,
  totalReferrals: true,
  referralProDaysRemaining: true,
  referralProExpiresAt: true,
  notifySignals: true,
  notifyPortfolio: true,
  notifyNews: true,
  notifyAchievements: true,
  notifyGoals: true,
  lastLoginAt: true,
  loginStreak: true,
  lastPasswordChangeAt: true,
  lastUsernameChangeAt: true,
  usernameChangeCount: true,
  isFirstLogin: true,
  hearAboutUs: true,
  investorProfile: true,
  userTitle: true,
  createdAt: true,
  updatedAt: true,
  isSuspended: true,
} satisfies Prisma.UserSelect;
